### ISSUE TITLE
Privacy IG

### ISSUE THREAD

**Issue by samuelweiler** [w3c/strategy#103]
The Privacy IG has been out of charter since Dec 2016, and the charter does not reflect current team contact(s).  The IG is functional(!), so I suggest we extend the charter, updating the contact(s).

**Comment by samuelweiler** [comment]
extended charter is expiring.  moving this back to the chartering tab.

**Comment by samuelweiler** [comment]
2019 charter draft: https://w3cping.github.io/administrivia/charter-draft.html

editable source: https://github.com/w3cping/administrivia/blob/master/charter-draft.html

**Comment by michael-n-cooper** [comment]
Accessibility has an interest in horizontally reviewing this horizontal review group. Therefore the "will seek horizontal review of deliverables" statement, and a liaison to APA WG, is requested.

**Comment by r12a** [comment]
None of the materials i skimmed while reviewing this charter mention anything related to differences across locales or languages.  Is this something that impinges on PING's scope?

**Comment by samuelweiler** [comment]
> Accessibility has an interest in horizontally reviewing this horizontal review group. Therefore the "will seek horizontal review of deliverables" statement, and a liaison to APA WG, is requested.

I'm fine with the horizontal review of deliverables - I'll add that.  I'm puzzled by the request for an APA liaison.  That seems like overkill?

**Comment by samuelweiler** [comment]
> None of the materials i skimmed while reviewing this charter mention anything related to differences across locales or languages. Is this something that impinges on PING's scope?

Language not so much.

Locale, or at least culture, impinges in a pretty major way because expectations around privacy are quite different around the globe.  I'm not sure what to say or do differently here - I'm cringing at the thought of "two Webs" or "two Internets" - one more easily surveillable, one less so.  Or one more tracking-friendly and one less so.  Does that context inspire further ideas?

**Comment by r12a** [comment]
I was rather hoping to get the feeling that the group would be aware of geographical, linguistic, or cultural differences, and take those into account (with the goal to avoid two Webs wherever possible), rather than view the world from a parochial perspective (too-often the case for groups of techies).  I didn't get any hints from the charter related to that. That was my concern.

**Comment by michael-n-cooper** [comment]
Our experience with horizontal review is that the generic boilerplate statement in charters doesn't do much in practice towards assuring horizontal review happens in a timely manner. When there are known horizontal interests in a group's work, we find an explicit liaison statement helps to remind principals of the need to coordinate on those issues. 

In the case of PING, the document "Mitigating Browser Fingerprinting in Web Specifications" has a definite accessibility relationship, as assistive technology and user customization settings increase the fingerprint surface dramatically. APA is reviewing this document and would have liked the opportunity to submit comments prior to it's most recent publication as a Note. Therefore an explicit liaison statement going forward seems appropriate.

**Comment by wseltzer** [comment]
Chartered: https://lists.w3.org/Archives/Public/public-new-work/2019Oct/0001.html
