### ISSUE TITLE
Synchronized Multimedia for Publications

### ISSUE THREAD

**Issue by iherman** [w3c/strategy#105]
EPUB3 uses a (fairly stripped down) version of SMIL for various purposes, primarily in the area of accessibility. The [Synchronized Multimedia for Publications Community Group](https://www.w3.org/community/sync-media-pub/) plans to look into OWP friendly ways to reproduce that minimal level of information. This is necessary because no browser implements SMIL (except for some features as part of their SVG implementations).

This CG _may_ lead to a WG proposal if the work is successful.

**Comment by svgeesus** [comment]
[Explainer](https://w3c.github.io/sync-media-pub/explainer.html)

**Comment by iherman** [comment]
There is a new WG charter in discussion which may use the [results of this CG](https://w3c.github.io/sync-media-pub/sync-media-lite) for further incubation. We are hoping to discuss this on our next WG call in December. In any case, the CG itself has more or less stopped its separate activity, so it is o.k. to close it.

**Comment by iherman** [comment]
Is there any more action I should take to effectively close that CG?


cc @ianbjacobs

**Comment by ianbjacobs** [comment]
Hi Ivan,

No further action by you is needed. We’ll be closing groups over the next couple of weeks. Thank you!

Ian

> On Nov 20, 2024, at 7:52 AM, Ivan Herman ***@***.***> wrote:
> 
> 
> Is there any more action I should take to effectively close that CG?
> cc @ianbjacobs
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

--
Ian Jacobs ***@***.***>
https://www.w3.org/People/Jacobs/
Tel: +1 917 450 8783

**Comment by iherman** [comment]
The CG has been officially closes. Closing this issue.
