### ISSUE TITLE
Physical Web interactions (e.g., transit, payment)

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/strategy#106]
Potential use cases for browser interactions
 * transit (ticketing)
 * payments (e.g., pay at the pump, candy machine)

**Comment by samuelweiler** [comment]
I expect to see the same tokens used for Web Authentication also be used for these two cases, but I don't see those as needing browser interactions - transit turnstiles aren't giving the user a general-purpose browser. Explain how this is a browser thing?

**Comment by ianbjacobs** [comment]
@samuelweiler wrote: "Explain how this is a browser thing?"

The use case I have in mind is this: I travel to a new city. I want to make a payment without downloading an app. I have payment credentials stored in my browser. Why can't I provide them seamlessly (to a server over my 3G connection)? 

I imagine something like this:

 * I enter the station and somehow get a URL to my OS (e.g., QR code, bluetooth beacon, etc.) .
 * The OS opens the browser that URL and I am prompted to make a payment. I push a button
    to make the payment.
 * I show the resulting QR code to the turnstyle.

Google removed support for Physical Web from Chome last fall [1], so I'm not sure there's any 
momentum for this.

Ian

[1] https://blog.beaconstac.com/2017/10/chrome-removes-physical-web-support-on-ios-android/

**Comment by ianbjacobs** [comment]
No action on this so closing.
