### ISSUE TITLE
CSS: Leading in the web

### ISSUE THREAD

**Issue by shalanah** [w3c/strategy#107]
Design has been pushed further and further in the web with CSS Grids and Flexbox, making it easier to create flexible grid structures that print designers have enjoyed for a long time. One item left remaining would be to easily achieve vertical rhythm and match print text more accurately. More specifically, adding `leading` to the web, and that its fall-back would be `line-height`.

**Comment by astearns** [comment]
@shalanah it would probably be better to bring up your proposal in an issue here: https://github.com/w3c/csswg-drafts/issues

Please take a look at https://drafts.csswg.org/css-line-grid/ and https://drafts.csswg.org/css-rhythm/ to see if either of those proposals meet the need you identify.

**Comment by shalanah** [comment]
@astearns Thanks so much, was trying to find the right spot to place this!
