### ISSUE TITLE
Privacy Workshop?

### ISSUE THREAD

**Issue by wseltzer** [w3c/strategy#11]
_From @tidoust on October 12, 2016 6:52_

null

_Copied from original issue: tidoust/strategy#3_

**Comment by wseltzer** [comment]
https://blog.mozilla.org/tanvi/2016/06/16/contextual-identities-on-the-web/ 
https://pad.w3ctag.org/p/2017-02-08-minutes.md

**Comment by samuelweiler** [comment]
closing this generic item
