### ISSUE TITLE
Two decades of Linked Data

### ISSUE THREAD

**Issue by draggett** [w3c/strategy#112]
Possible workshop on sharing experiences from 20 years of Linked Data. Annotations for Linked Data and other work arounds for weaknesses in how RDF handles reification, e.g. in relation to temporal, spatial, trust and provenance information. LinkedData transformation languages for mapping data between different vocabularies with overlapping semantics.

**Comment by iherman** [comment]
That sounds interesting! Are there possible sponsors for this?

Some other topics that just jump to my mind: relationships to other graph based modeling languages like property graphs; simpler rule based inference languages like n3, RDFS, OWL-RL, etc with Linked Data; vocabulary management (of course); versioning...

(I must admit that, at least out of nostalgia, I would love to be there, budget permitting:-)

**Comment by draggett** [comment]
I am hoping to get some funding from a EU project together with sponsorship, but this is still at a very early stage, so current focus is on assessing level of interest.

**Comment by sandhawke** [comment]
Seems quite relevant to credibility work.

The technology is in a weird state between obvious (use the URL of a page you talk about it) and never-implemented ideas (like how to handle that page changing).

**Comment by dontcallmedom** [comment]
did https://www.w3.org/Data/events/data-ws-2019/ basically address this? If so, should this be moved to Strategy Work concluded?
