### ISSUE TITLE
Progressive Font Enrichment

### ISSUE THREAD

**Issue by svgeesus** [w3c/strategy#117]
On the fly increasing the glyph repertoire of an already-downloaded font by requesting updates from a server and stitching them into the downloaded font.

Existing incubation with various experiments by Adobe, demonstrated at ATypI 2016; deployment on Typeket, deployment by Monotype, deployment by Google Fonts. However each one is a custom API; not designed for interop.

There is interest on a standardized, shared client-server API, which could be implemented natively or as a script in the browser. 

This would particularly help fonts for languages with large glyph repertoires (Chinese, Japanese, Korean) or languages with a Basic Latin+extras repertoire.

**Comment by svgeesus** [comment]
Horizontal review, especially from I18n, would be helpful in charter development and in requirements gathering.

**Comment by svgeesus** [comment]
[Draft charter for advance notice](https://www.w3.org/Fonts/WG/webfonts-2018.html)

**Comment by svgeesus** [comment]
Security and privacy implications of successive requests mentioned on 19 June strat call.

**Comment by wseltzer** [comment]
Chartered: https://lists.w3.org/Archives/Public/public-webfonts-wg/2018Dec/0000.html
