### ISSUE TITLE
Dataset Exchange (Vocabularies)

### ISSUE THREAD

**Issue by wseltzer** [w3c/strategy#12]
_From @tidoust on October 12, 2016 6:50_

https://www.w3.org/2016/11/sdsvoc/

_Copied from original issue: tidoust/strategy#2_

**Comment by philarcher1** [comment]
This workshop is really about the future of vocabulary management at W3C. This is an area we've looked at for years but never been able to make progress with. We need a lot of pieces in place, and funding. Almost as an aside, the EC's Publications Office is now supporting a tool called VocBench, a collaborative tool developed by the FAO, see http://aims.fao.org/vest-registry/tools/vocbench.

**Comment by wseltzer** [comment]
It would be great to sync with @swickr on the architectural considerations

**Comment by wseltzer** [comment]
Workshop report: https://www.w3.org/2016/11/sdsvoc/report

**Comment by wseltzer** [comment]
Advance notice: https://lists.w3.org/Archives/Member/chairs/2017JanMar/0066.html

**Comment by wseltzer** [comment]
DXWG draft charter:  https://www.w3.org/2017/dxwg/charter
Sent for AC Review 30 March, https://lists.w3.org/Archives/Member/w3c-ac-members/2017JanMar/0060.html
Review results (member-only): https://www.w3.org/2002/09/wbs/33280/DXWG_Charter/results (closes 30 April)

**Comment by wseltzer** [comment]
WG Chartered: https://www.w3.org/2017/dxwg/wiki/Main_Page
