### ISSUE TITLE
Coverage JSON

### ISSUE THREAD

**Issue by marqh** [w3c/strategy#122]
Coverage JSON was developed and publicised during  the work of the Spatial Data on the Web working group 
https://www.w3.org/2015/spatial/wiki/Main_Page

A W3 working note was published in July 2017
https://www.w3.org/TR/covjson-overview/

Implementations are building on this work.

There is a current project updating the ISO/OGC abstract specification ISO19123 Coverages.

If successful, this investigation would analyse CovJSON and feed back into the ISO19123 editing committee suggestions and clarifications.  
CovJSON would be harmonised with ISO19123 and the updates currently being drafted to that specification.
The CovJSON specification would be moved into W3 management.
The supporting vocabularies would be published in a http://w3.org domain.

Organisations interested in supporting this activity:
 * The Met Office in the UK http://metoffice.gov.uk

Engagement will be organised through the Spatial Data on the Web Interest Group 
https://www.w3.org/2017/sdwig/

Next Steps:
* Liaise with OGC and ISO to analyse the harmonisation of ISO19123 and CovJSON.
* Develop vocabularies to support the CovJSON encoding.
* Manage and review activities through the Spatial Data on the Web Interest Group.

**Comment by marqh** [comment]
@tidoust 
Hello François

Please may you review this ticket, following on from today's meeting, and consider any useful edits?
Once it is appropriate to, I assume you will add the appropriate labels and project links.

many thanks
mark

**Comment by tidoust** [comment]
@marqh Ticket looks good, thanks!

Moving the issue to Investigation phase as [resolved during the Spatial Data on the Web IG F2F](https://www.w3.org/2018/06/06-sdw-minutes.html#x07).

**Comment by 6a6d74** [comment]
@marqh 

Are you managing to make any progress on the next steps you identified?

> Next Steps:
> 
> 1. Liaise with OGC and ISO to analyse the harmonisation of ISO19123 and CovJSON.
> 2. Develop vocabularies to support the CovJSON encoding.
> 3. Manage and review activities through the Spatial Data on the Web Interest Group.

Also - you should set up a Project in the w3c/sdw repo where you can manage the work. This Issue (in the w3c/strategy repo) is just to keep track of status.

Thanks.

**Comment by marqh** [comment]
hello @6a6d74 

Progress on the next steps is limited so far.  

1. Liaison with the editing committee for 19123 to get hold of a detailed draft of the updates is still awaiting responses.  Some information has been provided, but it is lacking in detail.
2. Vocabulary development has not really started.

I have created a project under SDW
https://github.com/w3c/sdw/projects/11
and I will look to populate this with detailed tickets as elements of the work get underway.

mark

**Comment by 6a6d74** [comment]
@chris-little, @marqh ... progress is happening over in OGC, with agreement to host development of Coverage JSON within the OGC WCS SWG. 

@chris-little is currently writing a Charter and Plan of Work for the activity.

From my perspective, Coverage JSON is now 'pre-charter' following agreements at OGC - so I am moving this ticket along the funnel.

**Comment by 6a6d74** [comment]
@tidoust ... maybe I can't move stuff in the Strategy Funnel myself? Please could you move this ticket to "Chartering". Many thanks.

**Comment by tidoust** [comment]
I moved it to "Chartering". I'm noting here for clarity that this chartering phase happens in OGC, and not in W3C, because this step was more meant to track ongoing chartering activities at W3C. 

@wseltzer, should we flag that somehow or move it elsewhere to avoid confusion?
