### ISSUE TITLE
Web Driver re-charter

### ISSUE THREAD

**Issue by wseltzer** [w3c/strategy#126]

**Comment by wseltzer** [comment]
https://www.w3.org/2016/05/browser-testing-tools-charter.html 
WebDriver went to Rec in June 2018, update milestones: https://www.w3.org/TR/webdriver/

**Comment by sideshowbarker** [comment]
Rechartered https://lists.w3.org/Archives/Member/w3c-ac-members/2018OctDec/0057.html
