### ISSUE TITLE
Feature Policy

### ISSUE THREAD

**Issue by wseltzer** [w3c/strategy#129]
https://wicg.github.io/feature-policy/ 

Migrate to WebAppSec?

**Comment by sideshowbarker** [comment]
See https://github.com/WICG/feature-policy/issues/218

> It seems this API is starting to get quite a bit of traction: Looking at caniuse.com, it's partially or fully implemented in Chrome and Safari, and I've just been informed it's landing in Firefox - which is really amazing!
> 
> Have you all thought about moving this work to Web App Sec for formal standardization or do you feel it still needs more incubation?

**Comment by wseltzer** [comment]
Adopted by WebAppSec
