### ISSUE TITLE
Web & VR

### ISSUE THREAD

**Issue by wseltzer** [w3c/strategy#13]
_From @tidoust on October 12, 2016 6:49_

null

_Copied from original issue: tidoust/strategy#1_

**Comment by wseltzer** [comment]
https://www.w3.org/2016/06/vr-workshop/

**Comment by wseltzer** [comment]
@dontcallmedom @tidoust @sideshowbarker @svgeesus @wseltzer looking at workshop follow-up

**Comment by plehegar** [comment]
We have a draft charter. Shouldn't we move this to Chartering?

**Comment by wseltzer** [comment]
https://w3c.github.io/webvr-charter/vr-wg-charter.html

**Comment by wseltzer** [comment]
Advance notice sent https://lists.w3.org/Archives/Public/public-new-work/2017Mar/0009.html

**Comment by dontcallmedom** [comment]
(this was moved back to evaluation based on the [results of the AC review](https://lists.w3.org/Archives/Public/public-new-work/2017Sep/0000.html))

**Comment by koalie** [comment]
[W3C Workshop on WebVR Authoring: Opportunities and Challenges, December 5-7, Brussels, Belgium](https://www.w3.org/2017/09/webvr-authoring-workshop/)
