### ISSUE TITLE
Media encoder/decoder API

### ISSUE THREAD

**Issue by tidoust** [w3c/strategy#130]
Discussed in the context of [WebRTC vNext](https://www.w3.org/2018/06/19-webrtc-minutes.html#item05) exchanges during last WebRTC WG F2F. See [Encoders/Decoders slides](https://docs.google.com/presentation/d/17BVuVX4c3dPaNe_PzD54UiwUcP6FnKwsevUaVRGNi00/edit#slide=id.g3c72398134_0_735) presented during that meeting.

In WebRTC, the encoder/decoder is entangled with the transport mechanism. For good reasons as transmission can then benefit from insider codec and transport knowledge to prepare optimized packets. However, separating encoder/decoder from transport and exposing an encoder/decoder API may also makes sense in some cases. For instance:
- it would make it possible to distribute one stream to multiple transports, which can be useful in teleconference systems where a server/computer acts as [Selective Forward Unit](https://webrtcglossary.com/sfu/) (SFU).
- it would give apps more control over the jitter buffer and other performance parameters for cases where latency is critical (e.g. distributed orchestra)
- it would allow apps to add their own encryption scheme before transport
- it would allow apps to bring their own codec for WebRTC as described in #90
- it would allow to use the same transport for audio/video/data

Some questions that such work would raise:
- Relationship with MSE/EME and the Media recorder API? This seems to bring some redundancy.
- Similarly, for audio, relationship with the Web Audio API?
- Efficiency? As said, there are good reasons to combine encoder/decoder and transport in WebRTC scenarios.

The WebRTC WG might choose to work on this later on, although note that access to encoders/decoders would enable other non-WebRTC-related media use cases, so if other parties are interested, incubation/standardizion could be done in a different group. F2F outcome does not suggest strong support within the WG for now.

**Comment by tidoust** [comment]
The recently chartered [Media WG](https://www.w3.org/media-wg/) may choose to standardize an Encoders/Decoders API after some period of incubation, see [Potential normative specifications](https://www.w3.org/2019/05/media-wg-charter.html#potential-normative) section in Media WG charter.

**Comment by tidoust** [comment]
The [WebCodecs](https://github.com/wicg/web-codecs) proposal is now being incubated in the WICG.

Recent discussions during W3C's TPAC:
- [WebCodecs breakout session](https://w3c.github.io/tpac-breakouts/sessions.html#webcodecs)
- [Efficient media processing breakout session](https://w3c.github.io/tpac-breakouts/sessions.html#mediaprocessing) where WebCodecs was pointed out as core component of a solution in that space
- [WebCodecs session during the Media WG F2F](https://www.w3.org/2019/09/18-mediawg-minutes.html#item13)

**Comment by tidoust** [comment]
The Media WG issued a [call for consensus](https://github.com/w3c/media-wg/issues/24) to adopt WebCodecs as a WG deliverable and publish it as First Public Working Draft.

**Comment by dontcallmedom** [comment]
WebCodecs has been published as a FPWD; I believe this can be considered as done, so closing and moving to "strategy work concluded"
