### ISSUE TITLE
Strong Authentication & Identity Workshop

### ISSUE THREAD

**Issue by apowers313** [w3c/strategy#137]
A workshop to define W3C's vision for strong authentication & identity, align existing work (e.g. WebAuthn, CCG, DIDs, VCs, etc.), and identify next steps for authentication and identity on the web.

**Comment by wseltzer** [comment]
Workshop pages: https://www.w3.org/Security/strong-authentication-and-identity-workshop/
Report forthcoming.

**Comment by samuelweiler** [comment]
Draft report: https://docs.google.com/document/d/1QIFrWiyJ4Lcja0_i57PliU_zHOGoLiKjOug77OH_XcM/edit

**Comment by wseltzer** [comment]
Report published: https://www.w3.org/Security/strong-authentication-and-identity-workshop/report.html
