### ISSUE TITLE
Fonts IG or WG

### ISSUE THREAD

**Issue by wseltzer** [w3c/strategy#14]

**Comment by svgeesus** [comment]
With WOFF2 almost done, what comes next for WebFonts? There is high interest in OpenType 1.8 variable fonts but this work is already part of SS 4 Fonts. There is some interest in an open font subsetting API (similar to the proprietary API exposed by TypeKit, for example).

**Comment by svgeesus** [comment]
Wendy mentioned 3D fonts (beyond simple extrusion) in a VR context, coming out of the WebVR workshop.

**Comment by wseltzer** [comment]
Closing for now.
