### ISSUE TITLE
Web Share API

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/strategy#145]
* Spec: https://wicg.github.io/web-share/
* Explainer: https://github.com/WICG/web-share/blob/master/docs/explainer.md
* TAG design review: https://github.com/w3ctag/design-reviews/issues/170

> Enables a site to share data (text, URLs, images, etc) to an arbitrary destination of the user's choice. It could be a system service, a native app or another website. The goal is to enable web developers to build a generic "share" button that the user can click to trigger a system share dialog.

---

It’s supported in Safari Technology Preview and Chrome (on Android)

**Comment by ylafon** [comment]
See https://github.com/w3ctag/design-reviews/issues/179 (The TAG did also review Web Share Target API).

**Comment by ylafon** [comment]
At this is now a FPWD from Web Apps WG (see https://www.w3.org/TR/2019/WD-web-share-20191217/ ), this can be closed.
