### ISSUE TITLE
Possible Media WG to improve client-side processing of media

### ISSUE THREAD

**Issue by tidoust** [w3c/strategy#148]
There are a number of media-related incubation activities in the Web Platform Incubator Community Group (WICG) that aim at improving media playback functionalities:

- Media Source Extensions (MSE) v2 to add codec switching support (see [incubation description](https://github.com/wicg/media-source/#incubation-of-vnext-media-source-specification-features)) to allow splicing of heterogeneous streams. Provides better support for ad insertion scenarios in particular.
- Encrypted Media Extensions (EME) v2 to add Persistent Usage Record, HDCP detection, and Encryption scheme capability detection, see [proposal description](https://discourse.wicg.io/t/proposal-further-work-on-encrypted-media-extensions/2623) and the corresponding GitHub repositories [wicg/encrypted-media](https://github.com/WICG/encrypted-media/), [wicg/hdcp-detection](https://github.com/WICG/hdcp-detection) and [wicg/encrypted-media-encryption-scheme](https://github.com/WICG/encrypted-media-encryption-scheme)
- [Media Capabilities](https://wicg.github.io/media-capabilities/) to allow websites to make an optimal decision when picking media content for the user. Tracked in #87.
- [Media Playback Quality](https://wicg.github.io/media-playback-quality/), which had been taken out of MSE before publication to allow adaptive streaming optimizations. Tracked in #88
- [Media Session](https://wicg.github.io/mediasession/) to integrate with OS-wide media controls. Tracked in #86 
- [Picture in Picture](https://wicg.github.io/picture-in-picture/) to create a floating video window always on top of other windows.

These specifications are aimed at improving the processing of media for playback on the client. For the most part, they are either stable or have a stable scope, and are being tracked or incubated within main browser codebases by the same restricted set of people.

It may make sense to transition at least some of these specs to the Recommendation track at once and within the same group. This issue tracks that possibility.

The status of these specs will be discussed during the F2F of the Media & Entertainment Interest Group at TPAC next week during the [Current media incubations in W3C Community Groups](https://www.w3.org/2011/webtv/wiki/Face-to-face_meeting_during_TPAC_2018#14:00_-_14:30_Current_Media_Incubations_in_W3C_Community_Groups) slot.

**Comment by tidoust** [comment]
A [draft charter](https://w3c.github.io/charter-media-wg/) for a possible Media Working Group is being assembled. On top of the activities mentioned above, the following deliverable is also considered:
- Autoplay policy, described in #164

**Comment by tidoust** [comment]
The draft charter notes two additional potential normative specifications that the working group could adopt after a period of incubation:
- Audio Focus API: an API to allow web applications to manage their audio focus, to improve the audio-mixing of websites with native apps so they can play on top of each other or play exclusively.
- Encoders/Decoders API, described in #130

**Comment by wseltzer** [comment]
Chartered. https://www.w3.org/media-wg/
