### ISSUE TITLE
Audio Description

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/strategy#149]
The [Audio Description Community Group](https://www.w3.org/community/audio-description/) is working to develop an open standard file format to support audio description all the way from scripting to audio mixing. Spec GitHub repo is w3c/adpt 

Please could that be added to the strategy funnel?

**Comment by nigelmegitt** [comment]
TTWG [agreed](https://github.com/w3c/tt-reqs/issues/4#issuecomment-459305184) on Friday to adopt this in a Charter revision and work on it in 2019. I will add this to a draft Charter for WG review during March.  

@wseltzer does this mean it moves off Exploration?

**Comment by wseltzer** [comment]
Sure. It sounds as though it's at least Incubation, and headed toward Chartering. Let us know how the team can help, @nigelmegitt

**Comment by svgeesus** [comment]
This deliverable was [added to the Timed Text charter](https://www.w3.org/2019/11/timed-text-wg-charter.html#deliverables) which was [approved 28 Nov 2019](https://lists.w3.org/Archives/Member/w3c-ac-members/2019OctDec/0046.html)
