### ISSUE TITLE
Machine Learning on the Web

### ISSUE THREAD

**Issue by wseltzer** [w3c/strategy#150]
https://webmachinelearning.github.io/charter/
https://www.w3.org/community/webmachinelearning/

Deliverable: Web neural network API

**Comment by dontcallmedom** [comment]
Proposed workshop on the topic under preparation https://github.com/w3c/machine-learning-workshop/

**Comment by samuelweiler** [comment]
As discussed on the team-horizontal mailing list, horizontal review is presently being sought for the workshop, not the charter.

As a process thing, I encourage having everyone fill in the reg form, even if they (also) submit a position statement - I have a nagging sense that someone'e position statement will be overlooked...

From a security and privacy perspective, this looks scary.  Some is that you're citing getting data from existing APIs which are themselves problematic.  Some of that is how broad and vague the scope is.  If the workshop were instead about a set of concrete, well-scoped use cases, it might be easier to consider the privacy and security issues.  As it is.... this is too broad.

**Comment by michael-n-cooper** [comment]
grammar error "...brought to be the browser help..." not sure what was meant there. Otherwise a11y review is ok.

**Comment by r12a** [comment]
> What benefits and risks machine learning usage in browsers create from a privacy & security perspective? How can the risks be mitigated?
> How can machine learning primitives brought to be the browser help with improving accessibility of Web pages and Web applications?

Any reason i18n isn't mentioned?  Seems to me that machine learning is important for translation, summarising, name & keyword identification, and many other language technology applications, although it's not clear to me what are the use cases where the browser would be involved in machine learning for those types of technology.  Anyway, whatever is discussed needs to be multilingual in scope, and it seems that the workshop may benefit from making that either a leitmotiv or a focused session.

**Comment by NalaGinrut** [comment]
If the dataset is collected by the browser, will the training data source be distributed to other nodes that running the same framework? There's potential concern about privacy. 

If no, then the computation power of learning is very limited. 

If yes, then how to prevent sensitive privacy information be leaked?

It's better to see more explanation for the issue. Thanks!

**Comment by wseltzer** [comment]
Workshop concluded, [report](https://www.w3.org/2020/06/machine-learning-workshop/proceeding.html)
Advance notice of new charter in progress: https://lists.w3.org/Archives/Public/public-new-work/2020Oct/0001.html
