### ISSUE TITLE
WebGPU API Proposal (Apple)

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/strategy#152]
Spec: https://cdn.staticaly.com/gh/gpuweb/proposals/master/WebGPU-Apple/api-proposal.html
Source: https://github.com/gpuweb/proposals/blob/master/WebGPU-Apple/api-proposal.html

As far as I know, this proposal from Apple is the only concrete documented proposal for the WebGPU API itself (as opposed to the related-but-separate proposals for shading language).

So this is related to https://github.com/w3c/strategy/issues/68 but more concrete/specific.

**Comment by dontcallmedom** [comment]
closing since the activity is being recorded on #68
