### ISSUE TITLE
Constructable Stylesheet Objects

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/strategy#156]
Spec: https://wicg.github.io/construct-stylesheets/
Explainer: https://github.com/WICG/construct-stylesheets/blob/gh-pages/explainer.md

> We can provide an API for creating stylesheet objects from script, without needing style elements. Script can optionally add or remove rules from a stylesheet object. Each stylesheet object can be added directly to any number of shadow roots (and/or the top level document), which are in the same document tree where it is constructed on.

The key use case for this is with web components and the shadow DOM; it’s the same use case that the Shadow Piercing feature was meant to address.

**Comment by svgeesus** [comment]
[Latest WICG draft](https://wicg.github.io/construct-stylesheets/) dated Jan 2019. Have asked editors about plans to bring this to CSS WG.

**Comment by svgeesus** [comment]
Looks likely to be [merged into CSSOM1](https://github.com/w3c/csswg-drafts/issues/3433#issuecomment-573614058)

**Comment by svgeesus** [comment]
[Resolved](https://lists.w3.org/Archives/Public/www-style/2020Feb/0012.html) at CSS WG A Coruña F2F in Jan 2020 to merge this into CSSOM-1.

I don't think this needs Strat follow from here.
