### ISSUE TITLE
Badging API

### ISSUE THREAD

**Issue by tidoust** [w3c/strategy#165]
Proposed API allowing web applications to set a taskbar or home screen icon badge:
- [Explainer](https://github.com/WICG/badging/blob/master/explainer.md)
- [Draft spec](https://wicg.github.io/badging/)

**Comment by dontcallmedom** [comment]
the spec is now adoptable by the WebApps WG as part of their [latest charter](https://www.w3.org/2020/12/webapps-wg-charter.html#wicgspecs), so this feels like "concluded" to me.
