### ISSUE TITLE
Display locking

### ISSUE THREAD

**Issue by tidoust** [w3c/strategy#166]
A proposal to avoid janks during DOM updates by freezing rendering of a DOM element and its subtree while these updates are being done. See the [explainer](https://github.com/WICG/display-locking/blob/master/explainer.md)

**Comment by samuelweiler** [comment]
Explainer link is broken.

**Comment by xfq** [comment]
WICG repo: https://github.com/WICG/display-locking

**Comment by svgeesus** [comment]
[Explainer](https://github.com/WICG/display-locking/blob/master/explainer-contain-intrinsic-size.md) correct link

**Comment by dontcallmedom** [comment]
work now part of draft CSS specs: https://drafts.csswg.org/css-contain-2/#content-visibility https://drafts.csswg.org/css-sizing-4/#intrinsic-size-override (the other 2 items listed in the repo have migrated to become a possible HTML feature in WHATWG) - feels like "strategy work concluded".
