### ISSUE TITLE
Scroll-linked animations

### ISSUE THREAD

**Issue by tidoust** [w3c/strategy#167]
The [Scroll-linked Animations](https://wicg.github.io/scroll-animations/) specification defines a declarative mechanism based on CSS properties to adjust the user interface based on the current scroll position, for example to shrink the top navigation menu as the user starts scrolling, or to display a progress bar.

**Comment by svgeesus** [comment]
Current proposal doesn't cover all their use cases, but good to see [Avoiding cycles with layout](https://wicg.github.io/scroll-animations/#avoiding-cycles) is addressed as this has derailed other proposals in the past. Also nice that it extends the Web Animations model, so the theoretical underpinnings appear sound.

**Comment by tidoust** [comment]
The proposal was adopted by the CSS WG during TPAC, see [Scroll-linked animation draft](https://drafts.csswg.org/scroll-animations-1/) specification there.
