### ISSUE TITLE
Telemetry workshop

### ISSUE THREAD

**Issue by samuelweiler** [w3c/strategy#172]
Shivan Kaul Sahib <shivankaulsahib@gmail.com> expressed interest in a workshop on telemetry (at IETF104 in March 2019).  Shivan is taking the action to explore level of interest.

Some starting points:
- Prio, a system invented by Henry Corrigan-Gibbs and Dan Boneh: https://crypto.stanford.edu/prio/paper.pdf
- Mozilla's implementation: https://hacks.mozilla.org/2018/10/testing-privacy-preserving-telemetry-with-prio/
-  Frank Brockners and Benoît Claise's presentation at IETF104.
- Seda Guerses at KU Leuven

**Comment by wseltzer** [comment]
Rappor https://github.com/google/rappor

client-side differential privacy, more generally

**Comment by ShivanKaul** [comment]
Google now uses PROCHLO: https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/46411.pdf

It introduces the Encode, Shuffle, Analyze (ESA) architecture for privacy-preserving telemetry.

**Comment by samuelweiler** [comment]
Shivan suggests Aleksandra Korolova, University of Southern California.  She was a participant in the [2018 W3C Workshop on Permissions and User Consent](https://www.w3.org/Privacy/permissions-ws-2018/papers.html).

**Comment by samuelweiler** [comment]
The IETF is (probably) chartering a WG in this area.  ([PPM](https://datatracker.ietf.org/doc/charter-ietf-ppm/))  We'll follow the work there, but a workshop is not in the cards now.
