### ISSUE TITLE
Privacy Preserving Ad Click Attribution

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/strategy#178]
Spec: https://wicg.github.io/ad-click-attribution/
Explainer (blog post): https://webkit.org/blog/8943/privacy-preserving-ad-click-attribution-for-the-web/

> allow for ad click attribution while disallowing arbitrary cross-site tracking.

**Comment by wseltzer** [comment]
Under discussion in the Improving Web Advertising BG.
https://www.w3.org/community/web-adv/

**Comment by samuelweiler** [comment]
See also https://github.com/w3c/strategy/issues/222

**Comment by plehegar** [comment]
Closing since this has been subsumed by #222
