### ISSUE TITLE
W3C Workshop on Data Models for Transportation

### ISSUE THREAD

**Issue by tguild** [w3c/strategy#179]
Seeking horizontal and general review of workshop proposal.

Landing page:

https://www.w3.org/auto/events/data-ws-2019/

Cfp: 

https://www.w3.org/auto/events/data-ws-2019/cfp

**Comment by r12a** [comment]
I assume that locale-specific factors, such as driving-side, regulatory restrictions on data sharing and use, and differences in systems of units used (including mixed models), will all be well understood by the participants and any proposals they make. Other than that, i don't have any comments for the workshop preparation.

**Comment by wseltzer** [comment]
Report: https://www.w3.org/auto/events/data-ws-2019/report.html
