### ISSUE TITLE
RDF Literals and Base Directions

### ISSUE THREAD

**Issue by iherman** [w3c/strategy#181]
Find an appropriate solution to add the base direction (equivalent to HTML's `dir` attribute) to RDF's natural language literals.

**Comment by iherman** [comment]
This has been an issue that has plagued (and still does) many I18N reviews of Working Group documents that defined some sort of a vocabulary. These included (and includes) Web Annotation, Social Web, Web of Things, Publishing, JSON-LD, or Verifiable Claims. In short, while RDF has language literals (i.e., there is a possibility to add a BCP47 language tag to a string) there is no way to set a direction, and that meant that any vocabulary, say, for a Verifiable Credential, Publication Manifest, etc., can be properly internationalized. Half-baked solutions have been adopted, but none of them are satisfactory...

There have been discussions (e.g., around the [i18n note on strings on the Web](https://www.w3.org/TR/string-meta/) and recently an ad-hoc discussion round around a [document listing the possible options](https://w3c.github.io/rdf-dir-literal/), see also the meeting minutes on [2019-05-29](https://www.w3.org/2019/05/29-i18n-minutes.html) and [2019-06-05](https://www.w3.org/2019/06/05-i18n-minutes.html).

The conclusion of the discussion is two-fold:

1. The only _clean_ solution is to go back to the basis and solve the issue in RDF. The proposal is to do this in a very focused and short-lived Working Group doing that _and only that_ change in RDF.
2. Some intermediary measures, possibly looking forward to the outcome of the aforementioned working group, should be adopted in JSON-LD and, as a consequence, to VC and other documents.

**Comment by iherman** [comment]
Cc: @r12a @draggett @swickr @ashimura

**Comment by r12a** [comment]
Assuming that i didn't mess things up too badly, it may be useful to read https://github.com/w3c/rdf-dir-literal/issues/7#issuecomment-499152199 to get some additional background.

**Comment by iherman** [comment]
There is now a draft charter on the repo: https://w3c.github.io/rdf-dir-literal/draft-charter.html

**Comment by iherman** [comment]
Advance notice sent to the AC and chairs:

https://lists.w3.org/Archives/Member/w3c-ac-members/2019JulSep/0000.html

Also sent to other mailings list, e.g.,

https://lists.w3.org/Archives/Public/semantic-web/2019Jul/0003.html

**Comment by iherman** [comment]
There has been a [breakout session at TPAC](https://www.w3.org/2019/09/18-rdf-dir-literal-minutes.html). This led the JSON-LD WG to re-open the [issue of adding base direction to JSON-LD 1.1](https://github.com/w3c/json-ld-syntax/issues/11). On its F2F meeting at TPAC, the JSON-LD WG has accepted a series of resolutions, see the minutes of [Thursday](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-09-19-json-ld) and [Friday](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-20-19-json-ld) for the details.

The essence is: JSON-LD 1.1 will introduce a new keyword `@direction` that can be used, essentially, the same way as `@language`: can be part of the context to denote a global (i.e., default) value, and can also be used as part of an individual literal. 

The mapping to RDF will have, for now, several options to the user: dropping direction altogether, generate a [literal using a special datatype](https://w3c.github.io/rdf-dir-literal/#datatype-family), or generate a [compound blank node](https://w3c.github.io/rdf-dir-literal/#compound-literal) with the relevant terms. The RDF community may pick one of these solutions and standardize it. Until then this issue can be considered as parked.

**Comment by iherman** [comment]
What has been described in the [JSON-LD editors' drafts](https://github.com/w3c/strategy/issues/181#issuecomment-534555748)
