### ISSUE TITLE
Accessibility Guidelines Working Group

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/strategy#182]
Accessibility Guidelines Working Group is up for recharter. We hope to take the charter to W3M for 26 June.

Charter draft: https://raw.githack.com/w3c/wcag/charter-2019/charter.html

**Comment by r12a** [comment]
My only comment is that there is no longer an Internationalization Activity.  You may want to replace that with Internationalization Working Group, or lowercase the 'a'.

**Comment by michael-n-cooper** [comment]
I updated the reference, to the I18N WG.

**Comment by samuelweiler** [comment]
No objections re: security or privacy

**Comment by wseltzer** [comment]
Rechartered: https://lists.w3.org/Archives/Public/public-new-work/2019Dec/0013.html
