### ISSUE TITLE
Robots Exclusion Protocol (REP) "robots.txt" standardization

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/strategy#186]
Google has announced its intent to standardize robots.txt

> For 25 years, the Robots Exclusion Protocol (REP) was only a de-facto standard.
> (...)
> Today, we announced that we're spearheading the effort to make the REP an internet standard.

* [Google's robots.txt parser is now open source - Monday, July 01, 2019](https://webmasters.googleblog.com/2019/07/repp-oss.html)
* [A note on unsupported rules in robots.txt](https://webmasters.googleblog.com/2019/07/a-note-on-unsupported-rules-in-robotstxt.html)

**Comment by samuelweiler** [comment]
Here's the I-D: https://tools.ietf.org/html/draft-rep-wg-topic-00

**Comment by dontcallmedom** [comment]
now at https://datatracker.ietf.org/doc/html/draft-koster-rep-05 - since this seems to be well under way in IETF, I don't think there is anything for us to be doing or monitoring, so closing
