### ISSUE TITLE
WebTransport API

### ISSUE THREAD

**Issue by wseltzer** [w3c/strategy#189]
[Web Transport](https://github.com/wicg/web-transport), currently in WICG. [Explainer](https://github.com/wicg/web-transport/blob/master/explainer.md)

@vasilvv suggests that there may be interest in parallel work between W3C (API) and IETF (protocol).

**Comment by dontcallmedom** [comment]
https://w3c.github.io/webtransport-charter/charter.html
https://github.com/w3c/webtransport-charter

**Comment by svgeesus** [comment]
Is there a proposed chair, at this stage?

Is this for advanced work notice, or will it be sent to AC for review?

**Comment by dontcallmedom** [comment]
ongoing discussions regarding chair(s). Advance notice will be sent shortly.

**Comment by michael-n-cooper** [comment]
No comments from APA. Over to @brewerj to complete accessibility horizontal review.

**Comment by himorin** [comment]
No comment from i18n.

**Comment by samuelweiler** [comment]
No comments re: security nor privacy.

**Comment by brewerj** [comment]
Confirming no comments from Accessibility.

**Comment by samuelweiler** [comment]
Approved charter announced: https://lists.w3.org/Archives/Member/w3c-ac-members/2020JulSep/0039.html
