### ISSUE TITLE
WoT WG updated Charter

### ISSUE THREAD

**Issue by ashimura** [w3c/strategy#192]
The WoT WG is generating its updated Charter:
  http://w3c.github.io/wot/charters/wot-wg-charter-draft-2019.html

Most notably:
* Deliverables include updates to existing documents (Thing Description (Update) and Architecture (Update))
* Extensions to existing documents (Thing Description (Next)) and new deliverables (Interoperability Profiles and Discovery)

We're still finalizing the updates but would like to start the horizontal review in parallel because it would be better to start earlier than wait until it's completely fixed.

**Comment by michael-n-cooper** [comment]
APA WG is ok with this.

**Comment by ashimura** [comment]
Thanks a lot, Michael!

**Comment by plehegar** [comment]
@samuelweiler , any feedback on this charter?

**Comment by r12a** [comment]
I would appreciate it if the WoT group could make a concerted effort to consider whether there are any internationalization ramifications to their work, while developing their drafts.  This will probably produce better results than just asking the i18n group to review the various specs.  Is that something we can mention in the charter?

**Comment by r12a** [comment]
No other comments from i18n.

**Comment by ashimura** [comment]
Thanks a lot, @r12a !

As I mentioned on IRC, we'll have discussion within the WG and get back to you.

**Comment by ashimura** [comment]
@r12a I've talked with the WoT Chairs and we'd like to add a note on your point (about horizontal review) to the "5. Coordination" section.

Please see [PR907 on the wot repo](https://github.com/w3c/wot/pull/907).

**Comment by ashimura** [comment]
got a comment from @r12a to add a slight update for [PR907](https://github.com/w3c/wot/pull/907#issuecomment-555000046).

So we created a new Pullrequest [PR908](https://github.com/w3c/wot/pull/908) and added the change proposed by @12a .

Now the [updated draft WoT WG Charter](http://w3c.github.io/wot/charters/wot-wg-charter-draft-2019.html) should be ready for the next step :)

**Comment by wseltzer** [comment]
Chartered: https://lists.w3.org/Archives/Public/public-new-work/2020Jan/0011.html
