### ISSUE TITLE
Verifiable Claims WG in maintenance mode

### ISSUE THREAD

**Issue by plehegar** [w3c/strategy#193]
Draft is at:
  https://w3c.github.io/charter-drafts/verifiable-credentials-2019.html

Main goal is to maintain the VC spec.

Things to consider:
- Name of the Group. should we rename it?
- any restriction, such as meetings, time expected from the Chairs, out of scope, success criteria
- in communication, should we say more about the Community Group?
- in coordination, any update needed? should we least DiD? 

cc @ashimura

**Comment by plehegar** [comment]
Also cc @burnburn

**Comment by michael-n-cooper** [comment]
APA WG is ok with this.

**Comment by r12a** [comment]
Great to see a section on Internationalization in the vc-data-model doc.  No other comments.
