### ISSUE TITLE
Second Screen WG recharter

### ISSUE THREAD

**Issue by tidoust** [w3c/strategy#194]
Current charter of the Second Screen WG expires end of the year and the group is looking into rechartering:

- [Proposed charter for 2020-2021](https://w3c.github.io/secondscreen-charter/)
- [HTML diff between the current and proposed charters](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2F2014%2Fsecondscreen%2Fcharter-2018.html&doc2=https%3A%2F%2Fw3c.github.io%2Fsecondscreen-charter%2F)
- [HTML diff of material changes (excluding copy edits)](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Fsecondscreen-charter%2Feb7b6606870479956fac47e470640cdc59ec6dd6%2Findex.html&doc2=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Fsecondscreen-charter%2F5f672a0bf0f7a07013059eadd9c766703d1645ca%2Findex.html) [note added on 22 October 2019: this diff does not include the addition of the Open Screen Protocol, done later on. See the [HTML source changes](https://github.com/w3c/secondscreen-charter/pull/14/files)]

The proposed charter is being reviewed by the group itself and may still change.

Focus of the current period has been on the [Open Screen Protocol](https://webscreens.github.io/openscreenprotocol/) in the eponymous CG, initially triggered by feedback from the TAG on the need to have an open protocol to improve interoperability across devices. The incubation work of the first version of that set of protocols is now nearing completion. One question that is still open is whether to put the Open Screen Protocol in scope of the WG (the proposed charter does not include that for now).

cc @anssiko, @mfoltzgoogle

**Comment by michael-n-cooper** [comment]
APA WG is ok with this.

**Comment by tidoust** [comment]
> One question that is still open is whether to put the Open Screen Protocol in scope of the WG (the proposed charter does not include that for now).

The proposed charter got updated to put the Open Screen Protocol in scope of the WG. See the [HTML source changes](https://github.com/w3c/secondscreen-charter/pull/14/files). The Second Screen WG is reviewing this new version by 22 October.

@michael-n-cooper, thanks for the review, and note the change of scope!

**Comment by michael-n-cooper** [comment]
Thanks @tidoust APA is cool with this addition. We may need to review it as part of horizontal review.

**Comment by r12a** [comment]
I hope the group will do self-reviews for i18n not only on their own documents but also on the Open Screen Protocol work.

**Comment by r12a** [comment]
No other comments from i18n.

**Comment by tidoust** [comment]
[Group re-chartered](https://lists.w3.org/Archives/Public/public-secondscreen/2019Dec/0001.html).
See [approved charter](https://www.w3.org/2014/secondscreen/charter-2020.html) (same as the one initially proposed)
