### ISSUE TITLE
Web Payments Working Group Recharter

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/strategy#195]
Current charter of the Web Payments WG expires end of the year and the group is looking into rechartering. I am reviewing a <a href="https://www.w3.org/Payments/WG/charter-201910.html">draft charter</a> with the chairs; it may change. See <a href="https://www.w3.org/Payments/WG/charter-201910-diff.html">diff from current charter</a>.

I expect to issue a call for consensus to the WG (around 4 November) and the charter may change again.

I am also planning a blog post that will provide context for the review.

Ian

**Comment by r12a** [comment]
No comments from i18n review.

**Comment by michael-n-cooper** [comment]
APA WG has no charter comments but does have follow-up horizontal review input which will follow. Over to @brewerj to complete accessibility horizontal review.
