### ISSUE TITLE
Service Workers WG updated charter

### ISSUE THREAD

**Issue by ylafon** [w3c/strategy#196]
The SW WG is working on an updated charter to extend the current work, add new deliverables adopted from WICG, and move as soon as possible to Process 2020. 
See the draft here:

 https://w3c.github.io/charter-drafts/sw-2019.html

Thanks,

**Comment by samuelweiler** [comment]
What is the difference between the first two deliverables?  ("Service Workers" and "Service Workers 1")

**Comment by r12a** [comment]
No comments from i18n.

**Comment by ylafon** [comment]
Service Worker 1 is the subset intended to become a REC of Service Worker, so only things that are implemented and stable.

**Comment by wseltzer** [comment]
Chartered: https://lists.w3.org/Archives/Public/public-new-work/2020Jan/0008.html
