### ISSUE TITLE
Data Exchange WG recharter

### ISSUE THREAD

**Issue by plehegar** [w3c/strategy#197]
Please fill the template below to note a new charter or charter revision for strategy review.

# Charter Review

[Charter](https://w3c.github.io/dxwg/charter/index.html)

New charter allows for the next revision of DCAT. We're updating the chairs (placeholder but we have a candidate and awaiting confirmation). Note that  The Profiles Ontology document (published in /TR) is being moved to Working Group note.

What kind of charter is this? 

 - [x] New WG
 - [ ] New IG
 
If this is a new WG or IG charter request, link to [Advance Notice](), and any issue discussion: 

 - [x] Existing WG recharter
 - [ ] Existing IG recharter

If this is a charter extension or revision, link a [diff from previous charter](https://services.w3.org/htmldiff), and any issue discussion:

[HTML diff between the current and proposed charters](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2F2017%2Fdxwg%2Fcharter&doc2=https%3A%2F%2Fw3c.github.io%2Fdxwg%2Fcharter%2Findex.html)

Horizontal Reviews:
  - [ ] Accessibility (a11y)
  - [x] Internationalization (i18n)
  - [ ] Privacy
  - [x] Security

Communities suggested for outreach: 
Not needed. they're doing their own outreach.

Known or potential areas of concern?: 
The standard is used in governments, so limited impact but still useful.

Where would you like to see issues raised? (github preferred, email, ...)
github preferred

cc @pwin @draggett

**Comment by pwin** [comment]
Hi Philippe
Note that the 'reach' of the DCAT standard is not just 'government' in the
narrow sense, but is all open data (Google are committed to looking at DCAT
as the only other standard outside their own Schema.org for where they will
look for data catalogues) and in research data - e.g. Zenodo.  So perhaps
the 'limited impact but still useful' in the last point underplays the
importance and ambition of DCAT
Peter & Karen

**Comment by michael-n-cooper** [comment]
APA WG has no comments on this charter. Over to @brewerj to complete accessibility horizontal review.

**Comment by r12a** [comment]
No comments from i18n.

**Comment by wseltzer** [comment]
https://lists.w3.org/Archives/Public/public-new-work/2020Feb/0002.html Chartered
