### ISSUE TITLE
Geolocation, deliverables to D&S

### ISSUE THREAD

**Issue by svgeesus** [w3c/strategy#20]
Geolocation want to move some of their deliverables to Device & Sensor WG.

**Comment by plehegar** [comment]
I'm willing to help on this front. @dontcallmedom @ashimura , what's the best to get this done?

**Comment by dontcallmedom** [comment]
As discussed in another thread, the plan here is to bring future work on Geolocation to DAS.

The basic idea is to have a generic sensor-based geolocation API incubated and then brought to DAS. That plan might need to be accelerated if earlier or simpler revisions to the current Geo API are warranted (e.g. based on the [switch to secure contexts-only](https://groups.google.com/forum/#!topic/mozilla.dev.platform/BvcsTpAqIsQ)).

**Comment by philarcher1** [comment]
Please be sure to inform the Spatial Data WG about any and all developments in this direction. The Semantic Sensor Network Ontology folks have an obvious and direct interest.

**Comment by dontcallmedom** [comment]
I raised this as a point of discussion as part of the work on rechartering the Device and Sensors WG: https://github.com/w3c/dap-charter/issues/32 https://github.com/w3c/dap-charter/issues/31

**Comment by samuelweiler** [comment]
D&S is getting a 3 mo extension, planning to recharter in jan/feb 2018
