### ISSUE TITLE
Workshop on Media Production on the Web

### ISSUE THREAD

**Issue by tidoust** [w3c/strategy#205]
The Media & Entertainment Interest Group has started to discuss Media production on the Web to inform a use cases and requirements document on the topic.

The Interest Group is exploring different options to gather input from a wide range of perspectives. If exploration shows that there is enough interest in the topic, one of the options would be to organize a (possibly virtual) workshop.

See:
- The [Gather external input re: media production on the web](https://github.com/w3c/media-and-entertainment/issues/30) issue on the Media & Entertainment Interest Group issue tracker
- A [pull request](https://github.com/w3c/media-and-entertainment/pull/31) for a problem statement that could serve as initial sketch of a call for participation.
- Slides on [Professional media workflows on the web](https://www.w3.org/2011/webtv/wiki/images/8/88/M%2Be-web%2Bpro-workflows.pdf) presented at TPAC
- [Minutes of the discussion at TPAC](https://www.w3.org/2019/09/16-me-minutes.html#item07)

**Comment by tidoust** [comment]
The [problem statement](https://w3c.github.io/media-and-entertainment/media-production/problem-statement) is now available.

Completed with the "usual" text around logistic, this problem statement can be read as a call for participation for a possible workshop on the topic. Whether a workshop will take place is completely undecided for now. I would like to treat this as if that were the case though, and initiate horizontal reviews, which will be useful in any case.

Questions in the problem statement include considerations on accessibility, performance, and internationalization. The ones on accessibility and internationalization remain fairly generic though.

**Comment by himorin** [comment]
From i18n WG, no request on this problem statement.

**Comment by tidoust** [comment]
This workshop idea stalled last year, but activity has now resumed folllowing discussions in the Media & Entertainment IG. A draft CfP is available at:
https://www.w3.org/2021/03/media-production-workshop/

We're reaching out to companies of interest to assemble a program committee. Note workshop dates are very likely going to be modified (and pushed to September).

**Comment by samuelweiler** [comment]
I have reservations about two of the bullet items in the scope, and I'd like them to either be out of scope or hear clear justifications for including both:

> - Content security, including content encryption and forensic marking.
> - Content provenance and authenticity in production workflows.

**Comment by tidoust** [comment]
Thanks for the review @samuelweiler. Regarding your comment:

> * Content security, including content encryption and forensic marking.

This is one of the basic requirements that media companies raise in professional workflows (e.g. movie production): the ability to attribute leaks. A viable solution may be a mix of content encryption, watermarking and fine-grained access controls. I agree that some of it may be problematic in a general web environment. I disagree that excluding the topic will make the requirement go away though. Is there someone we could involve in in the workshop as participant or member of the program committee to make sure that all arguments get considered?


> * Content provenance and authenticity in production workflows.

I do not necessarily understand your concern here. Could you expand on that?

The bullet point was not necessarily clear. We're updating it to clarify that this is meant to be about production metadata, and generalizing the topic to creation and management of such metadata:
https://github.com/w3c/media-production-workshop/pull/4

That metadata can either be attached in-band or out-of-band. Both approaches create questions in terms of processing/preserving the metadata throughout professional workflows.

**Comment by samuelweiler** [comment]
> > * Content provenance and authenticity in production workflows.
> 
> I do not necessarily understand your concern here. Could you expand on that?

For both items: I'm particularly concerned that attribution (which might be implied by authenticity) could leak to general use cases.  e.g. I'm concerned about devices like cameras that might automatically attach identifiers and even digital signatures to images, which - if those cameras are in general use - could lead to privacy harms, when users are unaware of such automatic labelling.  It could also lead to a chilling effect - if a repressor can attribute a leak tape, it might lead to not leaking.

So while these privacy harms could be very acceptable in commercial media production cases, they become more of an issue if the technology is built into devices used by those who are seeking, for example, to hold the powerful to account.

**Comment by samuelweiler** [comment]
I appreciate the need for both items in the scope.  Here's a proposed bullet item to follow the two I objected to above, if you like:

> With the awareness that tracking, attribution, and authenticity proofs, as above, can pose privacy harms, particularly outside of professional use cases, mechanisms for limiting their use outside of professional contexts, making it clear when they're in use, and making them opt-in.

Removing objections, with the understanding that privacy awareness will be in scope.

**Comment by tidoust** [comment]
Status update:
- [Pre-recorded talks were published](https://www.w3.org/2021/03/media-production-workshop/talks.html) in October 2021.
- [GitHub issues](https://github.com/w3c/media-production-workshop/issues) were created from the talks and discussed online.
- [3 live sessions](https://www.w3.org/2021/03/media-production-workshop/agenda.html) took place in November 2021.
- A [draft report](https://www.w3.org/2021/03/media-production-workshop/report.html) is available. Gathering feedback from workshop participants before final publication.
