### ISSUE TITLE
CSS Print workshop

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/strategy#206]
Investigation
(note: this is a non-standard issue because this workshop is planned outside of W3C. I want to share it with strat team)
* The CSS WG is planning a [workshop](https://wiki.csswg.org/planning/print-workshop-2020) co-located with [XML Prague](https://www.xmlprague.cz/) to identify status of individual CSS Print related specs and see if and how they can be moved to REC status in order to send positive signal about maturity of technology to users and publishing industry
* Identify what is needed in order to move forward, 
** more editorial resources
**  create tests
** involvement from implementers
** identify incompatibilities between implementations
** collect new requirements (common vendor extension, features from [XSL-FO](https://www.w3.org/TR/xslfo20-req/WD-xslfo20-req.html) 

* Workshop is open to anyone. However, as it is organized as a part of XML Prague conference attendees need to register for XML Prague. For those who are not interested in other days of XML Prague there is special pass for only 40 € for workshop day. This will include lunch and two coffee breaks. 
* Next steps: Publicize to AC
/cc @dauwhe @rachelandrew

**Comment by svgeesus** [comment]
Resulted in [CSS Print Community Group](https://www.w3.org/community/cssprint/)
