### ISSUE TITLE
WebRTC 2020 charter

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/strategy#207]
New charter proposal, reviewers please take note.

# Charter Review

[Charter: Web Real-Time Communications Working Group Charter](https://w3c.github.io/webrtc-charter/webrtc-charter.html)

What kind of charter is this? Check the relevant box / remove irrelevant branches. 

* Existing 
 - [X] Existing WG recharter 
 - [ ] Existing IG recharter
[diff to previous 2018 charer](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2F2018%2F07%2Fwebrtc-charter.html&doc2=https%3A%2F%2Fw3c.github.io%2Fwebrtc-charter%2Fwebrtc-charter.html)
[discussion on changes](https://github.com/w3c/webrtc-charter/pull/53)

Horizontal Reviews (intended to be checked only by horizontal reviewers when they are satisfied with the charter)
  - [x] Accessibility (a11y)
  - [x] Internationalization (i18n)
  - [ ] Privacy
  - [ ] Security

Communities suggested for outreach: 
IETF?

Known or potential areas of concern?: 
The group will likely delay its rechartering to be able to benefit from process 2020.

Where would charter proponents like to see issues raised? (github preferred, email, ...)
[github](https://github.com/w3c/webrtc-charter/issues)

Anything else we should think about as we review?

**Comment by plehegar** [comment]
I believe that it is important to have a timeline for WebRTC 1.0 in the charter. At the minimum, it will highlight as part of the AC review and we need the WG to concur with the proposed timeline.

**Comment by r12a** [comment]
No i18n-related comments from me.

**Comment by dontcallmedom** [comment]
@plehegar there was no timeline for webrtc 1.0 and media capture and streams under the assumption they would be done by the time of the rechartering. If that assumption doesn't hold true, I absolutely agree their timeline needs to be in the charter.

**Comment by michael-n-cooper** [comment]
APA WG would like a liaison statement, as we are actively engaged in coordination and expect that to continue.

**Comment by dontcallmedom** [comment]
@michael-n-cooper could you suggest some text that you would like to see added to the charter to that effect? Thanks!

**Comment by michael-n-cooper** [comment]
Maybe: "The Accessible Platform Architectures identifies use cases for users with disabilities and reviews technologies to avoid unintentional introduction of barriers."

That might be enough for a liaison statement, but you could add if you want "Its [Media Accessibility User Requirements](https://www.w3.org/TR/media-accessibility-reqs/) and Real-Time Communication Accessibility User Requirements provide important input to this."

The latter document is under development now in APA and expected to be published as a Note-track first draft in about a month.

**Comment by svgeesus** [comment]
I notice a bunch of specs (including Audio Output Devices API ) in a "until another group take them over:" bucket. What is the story on those?

**Comment by dontcallmedom** [comment]
Ideally, the group would like a more focused group to take them over; but there isn't a good candidate at the moment (in particular, the Media WG has a different focus since it has less to do with media capture and transport), so for now, the safer approach seems to keep them in the group until such a group emerges.

**Comment by svgeesus** [comment]
OK, thanks. I wondered about possible overlap with the Web Audio WG, which also wants access to audio outputs (but with very different requirements than the "speakers or headphones" focus from Web RTC.

**Comment by michael-n-cooper** [comment]
APA review complete. Over to @brewerj to complete accessibility horizontal review.

**Comment by plehegar** [comment]
Goal is to start W3M review no later than July 15, and send the charter, with updated timeline and PP2020, around Aug 1.

**Comment by plehegar** [comment]
NOTE: take https://github.com/w3c/charter-drafts/pull/273 into account.

**Comment by brewerj** [comment]
Hi Dom, here are the links for the MAUR https://www.w3.org/TR/media-accessibility-reqs/ and the RAUR https://www.w3.org/TR/media-accessibility-reqs/ to please link to from section 3.1 of the draft charter https://w3c.github.io/webrtc-charter/webrtc-charter.html  Thanks, Judy

**Comment by samuelweiler** [comment]
Charter to AC for review: https://lists.w3.org/Archives/Public/public-new-work/2020Aug/0005.html
