### ISSUE TITLE
Distributed Tracing Working Group Charter 2020

### ISSUE THREAD

**Issue by plehegar** [w3c/strategy#214]
New charter proposal, reviewers please take note.

# Charter Review

[Charter:](https://www.w3.org/2020/03/proposed-distributed-tracing-wg.html)

What kind of charter is this? Check the relevant box / remove irrelevant branches. 

* Existing 
 - [x] Existing WG recharter 
 - If this is a charter extension or revision, link a [diff from previous charter](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2F2018%2F07%2Fdistributed-tracing.html&doc2=https%3A%2F%2Fwww.w3.org%2F2020%2F03%2Fproposed-distributed-tracing-wg.html), and any issue discussion:

Horizontal Reviews (intended to be checked only by horizontal reviewers when they are satisfied with the charter)
  - [x] Accessibility (a11y)
  - [x] Internationalization (i18n)
  - [ ] Privacy
  - [ ] Security

Communities suggested for outreach:
  The group is already in communication with Open Telemetry

Known or potential areas of concern?: 
  security, privacy

Where would charter proponents like to see issues raised? (github preferred, email, ...)
  https://github.com/w3c/distributed-tracing-wg/issues

Anything else we should think about as we review? 
  nope

@mtwo @SergeyKanzhelev @danielkhan

**Comment by michael-n-cooper** [comment]
APA WG has no comments. Over to @brewerj to complete a11y horizontal review.

**Comment by wseltzer** [comment]
@samuelweiler could you please take a look

**Comment by himorin** [comment]
No request from i18n WG.

**Comment by samuelweiler** [comment]
Opened two issues: https://github.com/w3c/distributed-tracing-wg/issues/35 and https://github.com/w3c/distributed-tracing-wg/issues/36

Summary: I want clarification on if and when these specs are intended to touch the browser and, if they do, a specific plan (or work item added) for how to request user consent for temporarily enabling support.

**Comment by brewerj** [comment]
Confirming no accessibility issues to address.

**Comment by samuelweiler** [comment]
The [snapshot circulated for internal review](https://www.w3.org/2020/03/proposed-distributed-tracing-wg.html), linked above, needs a marker that it's out of date.  

A [new shapshot](https://www.w3.org/2020/05/proposed-dt-wg-charter.html) has gone out for member review.

**Comment by samuelweiler** [comment]
Call for review was supposed to close on 23 June and has apparently been extended.

**Comment by wseltzer** [comment]
Re-charter approved: https://lists.w3.org/Archives/Public/public-new-work/2020Aug/0008.html
