### ISSUE TITLE
Devices and Sensors Working Group charter 2020

### ISSUE THREAD

**Issue by xfq** [w3c/strategy#216]
New charter proposal, reviewers please take note.

# Charter Review

[Devices and Sensors Working Group Draft Charter](https://w3c.github.io/dap-charter/DASCharter-2020.html)

 - [x] Existing WG recharter 
 - [Diff from previous charter](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2F2019%2F03%2Fdevices-sensors-wg-charter.html&doc2=https%3A%2F%2Fw3c.github.io%2Fdap-charter%2FDASCharter-2020.html)

Horizontal Reviews (intended to be checked only by horizontal reviewers when they are satisfied with the charter)
  - [x] Accessibility (a11y)
  - [x] Internationalization (i18n)
  - [x] Privacy
  - [x] Security

Communities suggested for outreach: 

Known or potential areas of concern?: security, privacy, implementation experience

Where would charter proponents like to see issues raised? [GitHub](https://github.com/w3c/dap-charter/issues)

Anything else we should think about as we review? 

Results of AC review: https://www.w3.org/2002/09/wbs/33280/das-2020/results#xsupport

**Comment by svgeesus** [comment]
I raised [an issue](https://github.com/w3c/dap-charter/issues/82) related to success criteria and already-released APIs.

**Comment by himorin** [comment]
No request from i18n WG.

**Comment by michael-n-cooper** [comment]
APA has no comments. Over to @brewerj to complete accessibility horizontal review.

**Comment by samuelweiler** [comment]
I very much like the new focus on privacy protection:

> As per the commitment to secure and privacy-preserving specifications, APIs in scope that expose sensitive data define normative mitigations to address any known security and privacy threats. These mitigations are developed and reviewed together with the security and privacy community and incorporated normatively into the respectively specifications.

I'm content with this charter.

**Comment by brewerj** [comment]
To complete to the accessibility, we'd just to make sure that APA WG gets a review request for three of the listed deliverables: Generic, Proximity, and Ambient Light. Thanks

**Comment by samuelweiler** [comment]
AC review closed on 19 June 2020 with one formal objection.  https://www.w3.org/2002/09/wbs/33280/das-2020/results#xsupport

Attempting to start public discussion(s) about that objection in https://github.com/w3c/dap-charter/issues

**Comment by samuelweiler** [comment]
Charter extended through October 2020.  https://lists.w3.org/Archives/Public/public-device-apis/2020Jul/0000.html

**Comment by xfq** [comment]
Charter approved: https://www.w3.org/2020/11/das-wg-charter.html
