### ISSUE TITLE
JSON-LD Maintenance Working Group

### ISSUE THREAD

**Issue by iherman** [w3c/strategy#219]
The charter of the [JSON-LD WG](https://www.w3.org/2018/json-ld-wg/) is getting towards its end (June 15 2020) and, at the moment, there are good hopes that the WG will properly finish its work by then. On its meeting on the 27th March 2020 the Group [passed a resolution](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2020/2020-03-27-json-ld#resolution3) to seek the creation of a Maintenance Working Group, taking over from the current WG with a new charter in June. 

A [draft initial charter](https://w3c.github.io/jsonld-wg-charter/) has been created.

@wseltzer @BigBlueHat @gkellogg @pchampin @azaroth42

**Comment by iherman** [comment]
Cc @plehegar

**Comment by BigBlueHat** [comment]
We might want to include a few more of the RDF related Community Groups in that list. There's a few:
https://www.w3.org/community/groups/?search=rdf (though that link won't likely work...it's generated by the site, but doesn't seem to result in what's intended when used 😕).

Top choices would be:
 - RDF JavaScript Libraries CG - https://www.w3.org/community/rdfjs/
 - RDF-DEV CG - https://www.w3.org/community/rdf-dev/

Both are relatively quite atm, but represent a key "surface areas" that need attention and maintenance and with which we should liaise.

**Comment by iherman** [comment]
@BigBlueHat could create a PR in the https://github.com/w3c/jsonld-wg-charter/ repo?

**Comment by iherman** [comment]
Closing this issue in favour of #220 (which uses the right template...)
