### ISSUE TITLE
TPWG

### ISSUE THREAD

**Issue by svgeesus** [w3c/strategy#22]

**Comment by wseltzer** [comment]
https://lists.w3.org/Archives/Public/public-tracking/2016Oct/thread.html

**Comment by wseltzer** [comment]
Charter review: https://www.w3.org/2002/09/wbs/33280/tracking-2016/results

**Comment by wseltzer** [comment]
Review closed with 26 supporters, one non-formal non-support (because there has been little adoption to-date), and 2 abstentions. That's more than 5% support, although several implementors did not participate in the review.

**Comment by wseltzer** [comment]
Chartered.
