### ISSUE TITLE
JSON-LD (maintenance) WG Charter

### ISSUE THREAD

**Issue by iherman** [w3c/strategy#220]
New charter proposal, reviewers please take note.

# Charter Review

[Charter:](https://w3c.github.io/json-ld-wg-charter/)

What kind of charter is this? Check the relevant box / remove irrelevant branches. 

* Existing 
 - [X] Existing WG recharter 
 - [ ] Existing IG recharter
 - If this is a charter extension or revision, link a [diff from previous charter](https://services.w3.org/htmldiff), and any issue discussion:

Horizontal Reviews (intended to be checked only by horizontal reviewers when they are satisfied with the charter)
  - [x] Accessibility (a11y)
  - [x] Internationalization (i18n)
  - [x] Privacy
  - [x] Security

Communities suggested for outreach: 

Known or potential areas of concern?: 

Where would charter proponents like to see issues raised? (github preferred, email, ...): github

Anything else we should think about as we review? The charter is minimal; the group is meant to be for a maintenance group following up the current [JSON-LD WG](https://www.w3.org/2018/json-ld-wg/). I am actually not even sure that a horizontal review is _really_ necessary...

---

This issue replaces #219

**Comment by michael-n-cooper** [comment]
APA has no comments. Over to @brewerj to complete accessibility horizontal review.

**Comment by himorin** [comment]
no comment from i18n.

**Comment by iherman** [comment]
@brewerj can you give your final nod on this charter? We may want to submit it to W3M soon; the idea would be to start the AC vote alongside the JSON-LD PR transition vote and that is coming up soon.

@wseltzer @samuelweiler the same request for the security/privacy review...

**Comment by brewerj** [comment]
Confirming that the accessibility horizontal review is completed. Thanks, Ivan

**Comment by samuelweiler** [comment]
No comments re: security nor privacy.

**Comment by iherman** [comment]
WG [has been announced](https://lists.w3.org/Archives/Member/w3c-ac-members/2020JulSep/0022.html). Closing.

**Comment by akuckartz** [comment]
@iherman That announcement is behind a login form :-(
