### ISSUE TITLE
WebAppSec Recharter

### ISSUE THREAD

**Issue by svgeesus** [w3c/strategy#23]

**Comment by wseltzer** [comment]
https://lists.w3.org/Archives/Public/public-webappsec/2016Oct/0036.html

**Comment by wseltzer** [comment]
Work-in-progress: https://lists.w3.org/Archives/Public/public-new-work/2016Dec/0009.html
Draft Charter: https://rawgit.com/w3c/webappsec/master/admin/webappsec-charter-2017.html

**Comment by wseltzer** [comment]
Existing charter extended for 3 months while recharter is sent for AC review.

**Comment by wseltzer** [comment]
Draft Charter now ready for horizontal reviews (a11y, i18n): https://rawgit.com/w3c/webappsec/master/admin/webappsec-charter-2017.html

**Comment by wseltzer** [comment]
accessibility review of charter completed

**Comment by wseltzer** [comment]
Sent for AC review: https://lists.w3.org/Archives/Public/public-new-work/2017Feb/0014.html
https://www.w3.org/2002/09/wbs/33280/WebAppSec17/results closes 20 Marach

**Comment by wseltzer** [comment]
Rechartered

**Comment by samuelweiler** [comment]
charter expiring soon.  reopening issue.
