### ISSUE TITLE
Machine Learning on the Web WG

### ISSUE THREAD

**Issue by wseltzer** [w3c/strategy#243]
New charter proposal, reviewers please take note.

# Charter Review

[Charter:](https://w3c.github.io/machine-learning-charter/charter.html)

What kind of charter is this? Check the relevant box / remove irrelevant branches. 

* New
 - [X] New WG 
 - [ ] New IG
 - If this is a new WG or IG charter request, link to [Advance Notice](https://lists.w3.org/Archives/Public/public-new-work/2020Oct/0001.html), and any issue discussion. [Workshop](https://github.com/w3c/strategy/issues/150)

Horizontal Reviews (intended to be checked only by horizontal reviewers when they are satisfied with the charter)
  - [ ] Accessibility (a11y)
  - [ ] Internationalization (i18n)
  - [ ] Privacy
  - [ ] Security

Communities suggested for outreach: 

Known or potential areas of concern?: 

Where would charter proponents like to see issues raised? ([github preferred](https://github.com/w3c/machine-learning-charter).

Anything else we should think about as we review?

**Comment by dontcallmedom** [comment]
I think this is a dup of #232

**Comment by wseltzer** [comment]
closing as duplicative
