### ISSUE TITLE
Service Workers 2021 Working Group Charter 2021

### ISSUE THREAD

**Issue by plehegar** [w3c/strategy#248]
New charter proposal, reviewers please take note.

# Charter Review

[Charter:](https://w3c.github.io/charter-drafts/sw-2020.html)

What kind of charter is this? Check the relevant box / remove irrelevant branches. 

* Existing 
 - [x] Existing WG recharter 
 - If this is a charter extension or revision, link a [diff from previous charter](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2F2020%2F01%2Fsw-charter.html&doc2=https%3A%2F%2Fw3c.github.io%2Fcharter-drafts%2Fsw-2020.html), and any issue discussion:

Horizontal Reviews: apply the Github label "Horizontal review requested" to request reviews for accessibility (a11y), internationalization (i18n), privacy, and security.  Also add a "card" for this issue to the [Strategy Funnel](https://github.com/w3c/strategy/projects/2).

Communities suggested for outreach:  none

Known or potential areas of concern:  none

Where would charter proponents like to see issues raised? (this strategy funnel issue, a different github repo, email, ...)
  https://github.com/w3c/charter-drafts

Anything else we should think about as we review? 
Nope

**Comment by plehegar** [comment]
cc @jakearchibald  @jungkees

**Comment by michael-n-cooper** [comment]
No comments from APA, we had reviewed with no comments the Service Workers spec. In a future charter with new deliverables, APA may have more interest. Over to @brewerj to complete accessibility horizontal review.

**Comment by samuelweiler** [comment]
Security and privacy reviews completed.  No security nor privacy issues on the charter.  Editorial issues on the charter filed in https://github.com/w3c/charter-drafts/issues/307
https://github.com/w3c/charter-drafts/issues/308
and
https://github.com/w3c/charter-drafts/issues/309.

Also filed two issues on the Service Workers spec.

I prefer to see more than one chair for most WGs, and I'm disappointed to see only one here.

**Comment by himorin** [comment]
No comment/request from i18n.

**Comment by michael-n-cooper** [comment]
APA has no comments. Over to @brewerj to complete accessibility horizontal review.

**Comment by plehegar** [comment]
@samuelweiler , regarding the Chairs, this is still under discussion. @ylafon has an action item from W3M.

**Comment by dontcallmedom** [comment]
[rechartered](https://lists.w3.org/Archives/Public/public-new-work/2021May/0003.html)
