### ISSUE TITLE
Media & Entertainment Interest Group rechartering

### ISSUE THREAD

**Issue by tidoust** [w3c/strategy#257]
New charter proposal, reviewers please take note.

# Charter Review

[Charter: Media & Entertainment Interest Group](https://w3c.github.io/media-and-entertainment/charters/charter-2021.html)

This is a recharter for an [existing IG](https://www.w3.org/2011/webtv/).

Other useful links:
- [Diff from previous charter](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2F2019%2F06%2Fme-ig-charter.html&doc2=https%3A%2F%2Fw3c.github.io%2Fmedia-and-entertainment%2Fcharters%2Fcharter-2021.html)
- [Discussion issue](https://github.com/w3c/media-and-entertainment/issues/43)

Feel free to raise issues in the group's [issue tracker](https://github.com/w3c/media-and-entertainment/issues) or directly in the [discussion issue](https://github.com/w3c/media-and-entertainment/issues/43)

Draft charter may still be refined based on discussions in the IG. On top of aligning the text with the latest charter template, the current draft shuffles text around, notably to make sure that the scope section only talks about the actual scope. The scope itself has not changed.

**Comment by samuelweiler** [comment]
Copied from https://github.com/w3c/media-and-entertainment/issues/52:


> I appreciate why you didn't take the charter template text re: horizontal review - this is, after all, an IG that doesn't produce specifications.
> 
> That said, the replacement text in section 4 is odd.
> 
> It calls for HR for "all topics discussed within the group". I suspect that should instead be "all documents produced by the group". It then goes on to talk about "specifications", including mentioning "...major standards-track document transition...". I would be happy to see HR review on the IG's Notes, but if they're indeed not producing specifications, we should clean this text up.
> 
> Likewise, section 3.2 should probably drop "Test suite and implementation report for the specification".

I have a slight preference for still doing HR on the deliverables, in which case I would like the security and privacy considerations sections in the docs (even though they're not specifications).  But you could persuade me to skip HR on Notes.

**Comment by michael-n-cooper** [comment]
APA has no comments, it looks good for a11y. Over to @brewerj to complete accessibility horizontal review.

**Comment by himorin** [comment]
i18n would appreciate that MEIG is willing to invite HR for draft IG Notes (and topics within), and would want to provide insights from i18n point of view for these opportunities.
We have no other comment/request, and would mark this as i18n review completed.

**Comment by tidoust** [comment]
Thanks all for reviews. The draft charter now uses the right boilerplate text for coordination.
@samuelweiler Are there other security and privacy issues that need to be resolved?

**Comment by samuelweiler** [comment]
> Thanks all for reviews. The draft charter now uses the right boilerplate text for coordination.
> @samuelweiler Are there other security and privacy issues that need to be resolved?

*shrug* Since the IG isn't producing specs, no, nothing else.

It still feels clumsy to ask for HR in the context of recommendation-track process, when the IG isn't producing rec-track docs, but I'll leave it to others to yell if it bugs them.

**Comment by tidoust** [comment]
> It still feels clumsy to ask for HR in the context of recommendation-track process, when the IG isn't producing rec-track docs, but I'll leave it to others to yell if it bugs them.

Well, despite what I was trying to achieve in the first place when I tried to drop it, I think the wording could actually prove useful in the end because the IG could one day decide to develop non-normative guidelines that end up being published as Recommendations.

**Comment by samuelweiler** [comment]
> > It still feels clumsy to ask for HR in the context of recommendation-track process, when the IG isn't producing rec-track docs, but I'll leave it to others to yell if it bugs them.
> 
> Well, despite what I was trying to achieve in the first place when I tried to drop it, I think the wording could actually prove useful in the end because the IG could one day decide to develop non-normative guidelines that end up being published as Recommendations.

I don't know how to deal with this with the minimum of work (or extra words in the charter), but I see that the [patent disclosures section](https://w3c.github.io/media-and-entertainment/charters/charter-2021.html#patentpolicy) specifically says the IG doesn't publish on the Rec track.  If it does produce Recs, that probably needs to be fixed, and we should probably copy over the other text from the [success criteria section of the template.](https://w3c.github.io/charter-drafts/charter-template.html#success-criteria) All of that seems like a pain.

**Comment by samuelweiler** [comment]
Filed as https://github.com/w3c/media-and-entertainment/issues/59: 

> Section 3:
>
>> The group will also maintain a public list of the media features on the Web that it is tracking and investigating.
>
> Can we provide a link to that list?

**Comment by tidoust** [comment]
> Filed as w3c/media-and-entertainment#59:

Mention dropped from the draft charter. The group is using GitHub labels more consistently nowadays to identify topics it tracks, but that does not seem to be something very interesting to call out in a charter.

**Comment by wseltzer** [comment]
Picking up on @samuelweiler 's comments, I was thrown by that review paragraph too.
https://github.com/w3c/media-and-entertainment/pull/62
 How can we improve it, if we don't want to drop it altogether?

**Comment by tidoust** [comment]
I agree that the section is clumsy. Striking it entirely seems clumsy too though. Horizontal activities likely want to see something in the charter that gives them confidence that IG Notes that the group may produce will have undergone some level of scrutiny from horizontal groups. The charter mentions horizontal considerations in success criteria but the text there does not encourage reaching out to dedicated groups.

One possible solution is to adjust the wording of the paragraph to IG Notes. That effectively forces the IG to run horizontal reviews on Notes. That may be a bit overkill in some cases but follows the spirit of the previous text.

Using the term "deliverable" instead of "specification" to avoid confusion with Rec-track specifications, and adjusting the text to Note steps, the paragraph would then become:

> For all deliverables, this Interest Group will seek [horizontal review](https://www.w3.org/Guide/documentreview/#how_to_get_horizontal_review) for accessibility, internationalization, performance, privacy, and security with the relevant Working and Interest Groups, and with the [TAG](https://www.w3.org/2001/tag/). Invitation for review must be issued during each major document transition, including [FPWD](https://www.w3.org/Consortium/Process/#RecsWD) and [IG Note](https://www.w3.org/Consortium/Process/#WGNote). The Interest Group is encouraged to engage collaboratively with the horizontal review groups throughout the development of each deliverable. The Interest Group is advised to seek a review at least 3 months before first entering [IG Note](https://www.w3.org/Consortium/Process/#WGNote) and is encouraged to proactively notify the horizontal review groups when major changes occur in a deliverable following a review.

**Comment by chrisn** [comment]
Thanks @tidoust. I don't think we sought HR for the group's last published Note, and if it's not strictly required I'd like to keep the flexibility. That said, if HR groups have already reviewed the charter with the previous wording, then I'm OK with your proposed text - which scopes it to deliverables rather than specifications.

**Comment by tidoust** [comment]
A middle ground may actually be to cut the paragraph in the middle... That is, we could perhaps drop the first part that mandates horizontal reviews, and keep the text that encourages them, leading to something like:

> The Interest Group is encouraged to engage collaboratively with the [horizontal review](https://www.w3.org/Guide/documentreview/#how_to_get_horizontal_review) groups for accessibility, internationalization, performance, privacy, and security, and with the [TAG](https://www.w3.org/2001/tag/), throughout the development of each deliverable. The Interest Group is advised to seek a review at least 3 months before first entering [IG Note](https://www.w3.org/Consortium/Process/#WGNote) and is encouraged to proactively notify the horizontal review groups when major changes occur in a deliverable following a review.

**Comment by chrisn** [comment]
This sounds good to me, if others are also happy with it.

**Comment by tidoust** [comment]
@chrisn pointed me to the recently approved [Web & Networks IG charter](https://www.w3.org/2021/04/web-networks-charter.html#coordination) that has text that constrains the group into horizontal reviews for Notes. I'd be tempted to follow that example and leave text as it currently is.

**Comment by chrisn** [comment]
I'm OK with leaving as it is. If there is a general preference from horizontal review groups to review IG Notes, perhaps this could be raised as a process issue.

**Comment by dontcallmedom** [comment]
[Group rechartered](https://lists.w3.org/Archives/Public/public-new-work/2021Jun/0008.html)
