### ISSUE TITLE
Media Working Group Rechartering

### ISSUE THREAD

**Issue by tidoust** [w3c/strategy#258]
New charter proposal, reviewers please take note.

# Charter Review

[Charter: Media Working Group](https://w3c.github.io/charter-media-wg/)

This is a recharter for an [existing WG](https://www.w3.org/media-wg/).

Other useful links:

- [Diff from previous charter](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2F2019%2F05%2Fmedia-wg-charter.html&doc2=https%3A%2F%2Fw3c.github.io%2Fcharter-media-wg%2F)
- [Dedicated repository for discussions](https://github.com/w3c/charter-media-wg/)

The group expects to publish a couple of specs to /TR before the current charter expires, which means links in the Deliverables section will need to be updated. Other parts may still be adjusted based on discussions within the Media WG.

The current draft charter does not introduce any change to the scope of the group. It adds the in-scope WebCodecs specification to the list of deliverables, which the working group just resolved to adopt. It also drops the persistent usage record session feature for EME, which the group no longer intends to add to the spec.

**Comment by samuelweiler** [comment]
The security and privacy text in section 3 does not match the current template.  Full review forthcoming.

**Comment by himorin** [comment]
No comment/request from i18n.

**Comment by samuelweiler** [comment]
I've filed three issues on this charter, most importantly a [blanket issue re: how to do capability detection and negotiation](https://github.com/w3c/charter-media-wg/issues/20) which touches many of the groups specs and 2 of the 3 proposed additions to EME.

There's also an issue about the other EME extension: https://github.com/w3c/charter-media-wg/issues/19.  

And another about the sec and privacy charter text, which still doesn't match the template. https://github.com/w3c/charter-media-wg/issues/16

I'm not sure I'm done with this HR review - there's a great deal of concerning subject matter in this WG, and I haven't even said anything about EME on the whole - but I wanted to get these issues into your hands for consideration now.

**Comment by samuelweiler** [comment]
Thank you for the responses on the capability negotiation and detection issue.  We agreed "For features that allow detection and/or negotiation of capabilities, the group will document architectural alternatives, particularly ones that minimize fingerprinting surface, and seek horizontal review as it makes its choice(s) among the alternatives."   I encourage the WG to seek early privacy review for the EME issues.

While I remain skeptical of doing further EME work, I'm not seeking to block the charter.

**Comment by plehegar** [comment]
There is a a suggestion to collaborate with the Open UI CG on audio/video UI controls.

**Comment by tidoust** [comment]
Closing as concluded
