### ISSUE TITLE
High latency, Low-bandwidth Web (such as Mobile)

### ISSUE THREAD

**Issue by svgeesus** [w3c/strategy#27]

**Comment by wseltzer** [comment]
Focus on the use case of low-bandwidth, high-latency environments (also covered by the AMP topic?)

**Comment by brewerj** [comment]
Here is some current work in mobile accessibility. Are there other areas of current W3C mobile work that we can coordinate with? 
In progress: https://www.w3.org/WAI/GL/mobile-a11y-tf/
and background on some other mobile accessibility work: https://www.w3.org/WAI/mobile/

**Comment by svgeesus** [comment]
The [Progressive Font Enrichment: Evaluation Report](https://www.w3.org/TR/2020/NOTE-PFE-evaluation-20201015/) specifically simulates high latency situations when downloading web fonts

**Comment by svgeesus** [comment]
Nothing specific to do here
