### ISSUE TITLE
Verifiable Credentials WG Rechartering

### ISSUE THREAD

**Issue by iherman** [w3c/strategy#279]
The Charter of the VC WG runs out at the end of the year. Discussions have begun in the WG whether the current (maintenance) charter should be simply renewed, or whether more substantial work would be proposed.

**Comment by plehegar** [comment]
https://github.com/w3c/vc-wg-charter is where the new charter is developed.

**Comment by iherman** [comment]
I would prefer to have a first, albeit rough, draft for the charter before going there...

@brentzundel

**Comment by plehegar** [comment]
(waiting on DiD)

**Comment by iherman** [comment]
# Charter Review Request

[Charter:](https:w3c.github.io/vc-wg-charter/) https:w3c.github.io/vc-wg-charter/

What kind of charter is this? Check the relevant box / remove irrelevant branches. 

* Existing 
 - [x] Existing WG recharter 

The diff does not really make sense in this case: the [current charter](https://www.w3.org/2020/12/verifiable-credentials-wg-charter.html) is for a maintenance Working Group, whereas the current one is for a full-blown Working Group. 

- Issues are at https://github.com/w3c/vc-wg-charter/issues
 
Horizontal Reviews: apply the Github label "Horizontal review requested" to request reviews for accessibility (a11y), internationalization (i18n), privacy, and security.

There is already a [card on the Strategy Funnel](https://github.com/w3c/strategy/issues/279)

Communities suggested for outreach: 

- Credentials Community Group

Known or potential areas of concern: 

- n/a

Where would charter proponents like to see issues raised? (this strategy funnel issue, a different github repo, email, ...)
    - The [charter repo issues](https://github.com/w3c/vc-wg-charter/issues)

Anything else we should think about as we review?

**Comment by himorin** [comment]
correct charter link: https://w3c.github.io/vc-wg-charter/

**Comment by samuelweiler** [comment]
> ... the current charter is for a maintenance Working Group, whereas the current one is for a full-blown Working Group.

Presumably you mean the proposed charter is for a full-blown WG.

I've done a first pass-review.  Please tag me to take another look after the scope is clarified (https://github.com/w3c/vc-wg-charter/issues/59).  I filed several issues, some editorial, some more substantive.  
https://github.com/w3c/vc-wg-charter/issues/52 
https://github.com/w3c/vc-wg-charter/issues/53 
https://github.com/w3c/vc-wg-charter/issues/55 
https://github.com/w3c/vc-wg-charter/issues/56 
https://github.com/w3c/vc-wg-charter/issues/57 
https://github.com/w3c/vc-wg-charter/issues/58 
https://github.com/w3c/vc-wg-charter/issues/59

**Comment by iherman** [comment]
Ack @samuelweiler. I had a first go at the issues with some 'triage' (calling out to those co-editors of the charter who should chime in), see my comments there.

Thanks.

**Comment by samuelweiler** [comment]
Thank you, @iherman, for digging into those so quickly.

**Comment by iherman** [comment]
Status: some comments came in at a later stage, which led to a flurry of discussion in the WG. There are, at this moment, [10 PRs to consider](https://github.com/w3c/vc-wg-charter/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc) (although they are interrelated, ie, solving one of those may make a number of others moot).

Difficult to judge when the charter proposal will reflect a WG consensus so that it could go to W3M. Second half of March, maybe?

**Comment by michael-n-cooper** [comment]
@lwohlberg to review for APA

**Comment by iherman** [comment]
The [charter](https://w3c.github.io/vc-wg-charter/) has got a [WG agreement](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-03-30-vcwg#resolution2); a request for W3M review has been sent out.

**Comment by michael-n-cooper** [comment]
APA would like a liaison statement, worded something like "Coordinate on accessibility use cases for verifiable credentials, and work jointly on a successor publication to inaccessible CAPTCHAs."

**Comment by iherman** [comment]
@michael-n-cooper, on the operative side: would you raise an issue in the VC Charter proposal's [issue list](https://github.com/w3c/vc-wg-charter/issues) or should I do it?

Personally (but I think that would be the reaction of many in the group) I would be interested in more details because, frankly, I did not realize VC-s could be helpful in APA work. What kind of application do you have in mind for a post-CAPTCHA world?

**Comment by iherman** [comment]
@michael-n-cooper see the comments on https://github.com/w3c/vc-wg-charter/issues/108, please.

**Comment by iherman** [comment]
Charter is under AC review: https://lists.w3.org/Archives/Member/w3c-ac-members/2022AprJun/0031.html
