### ISSUE TITLE
more elegent alternative to data-* attributes

### ISSUE THREAD

**Issue by therealadityashankar** [w3c/strategy#280]
So I was wondering if there could be a more "elegant" custom attribute alternative compared to the data-* attribute,

# Why?
Because people simply choose to ignore this rule in case attributes look too ugly to them, given that normal attributes work just fine instead of data-*, [vuejs does exactly this](https://v3.vuejs.org/guide/introduction.html#conditionals-and-loops) (context: VueJS can be used via a CDN too)

further, I think that, when making more attributes which use native components, having an easier way to write it would be easier

so for example, recently I was making a XHR web-component library that is supposed to change the native attributes/content of the elements,
and obviously, the native element needs a method to indicate that its attribute can be changed

I feel the developer experience of the users of my library could vastly improve with the addition of such a change

# Example in consideration
```html
<x-abc>
    <img --change="src:source-zone" src="./somewhere-over-the-rainbow"/>
    <span --change="content:other-source"></span>
</x-abc>
```
versus
```html
<x-abc>
    <img data-change="src:source-zone" src="./somewhere-over-the-rainbow"/>
    <span data-change="content:other-source"></span>
</x-abc>
```

consider 

## Suggested alternatives
CSS style `--` prefix, or `?` prefix, or something similar

I humbly ask the Web overlords to consider my request ❤️ 🥺

**Comment by marcoscaceres** [comment]
Hi @therealadityashankar. We appreciate your input, but this repo is for more general W3C admin stuff. 

Two options for you however. As the HTML spec is the one that standardizes data-* attributes, I suggest reposting your proposal here:
http://github.com/whatwg/html/issues/

Alternatively, you can post it for discussion at the WICG:
https://discourse.wicg.io
