### ISSUE TITLE
Charter proposal: Decentralized Identifier Working Group Charter

### ISSUE THREAD

**Issue by iherman** [w3c/strategy#281]
New charter proposal, reviewers please take note.

# Charter Review: Decentralized Identifier Working Group Charter

[Charter: https://w3c.github.io/did-wg-charter/](https://w3c.github.io/did-wg-charter/)

What kind of charter is this? Check the relevant box / remove irrelevant branches. 

 - [x] Existing WG recharter as a maintenance WG

[Diff from previous charter](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2F2020%2F12%2Fdid-wg-charter.html&doc2=https%3A%2F%2Fw3c.github.io%2Fdid-wg-charter%2F). But the diff does not really make sense in this case. The previous (ie, current) charter is: https://www.w3.org/2020/12/did-wg-charter.html.

Issues at:

- https://github.com/w3c/did-wg-charter
- WG discussions:
    - [2021-07-20](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-07-20-did#section5) 
    - [2021-08-03](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-08-03-did#section4)

Horizontal Reviews: apply the Github label "Horizontal review requested" to request reviews for accessibility (a11y), internationalization (i18n), privacy, and security.  Also add a "card" for this issue to the [Strategy Funnel](https://github.com/w3c/strategy/projects/2).

Communities suggested for outreach: 

- Credentials Community Group

Known or potential areas of concern: 

n/a

Where would charter proponents like to see issues raised? (this strategy funnel issue, a different github repo, email, ...)

- https://github.com/w3c/did-wg-charter/issues

Anything else we should think about as we review? 

None

---

cc: @brentzundel @msporny @burnburn

**Comment by iherman** [comment]
Can we issue an advanced notice? Actually, is this a requirement for a maintenance WG?

**Comment by plehegar** [comment]
we should send an advance notice indeed. @wseltzer ?

**Comment by wseltzer** [comment]
Sure, now that there's something to point at, please send the advance notice @iherman

**Comment by iherman** [comment]
> Sure, now that there's something to point at, please send the advance notice @iherman

Done, see https://lists.w3.org/Archives/Team/team-strat/2021Aug/0005.html

**Comment by himorin** [comment]
No comment/request from i18n.

**Comment by samuelweiler** [comment]
No security or privacy issues.

**Comment by michael-n-cooper** [comment]
APA would like to draw attention to recent updates to https://www.w3.org/TR/turingtest/. There are [issues](https://github.com/w3c/captcha-accessibility/issues) filed on this on which APA would like to collaborate with DID.
