### ISSUE TITLE
ARIA WG recharter

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/strategy#282]
New charter proposal, reviewers please take note.

# Charter Review

[Charter:](https://raw.githack.com/w3c/aria/charter-2021/charter.html)

What kind of charter is this? Check the relevant box / remove irrelevant branches. 

* New
 - New WG 
 - New IG
 - If this is a new WG or IG charter request, link to [Advance Notice](), and any issue discussion: 

* Existing 
 - [x] Existing WG recharter 
 - Existing IG recharter
 - If this is a charter extension or revision, link a [diff from previous charter](https://services.w3.org/htmldiff), and any issue discussion:

Horizontal Reviews: apply the Github label "Horizontal review requested" to request reviews for accessibility (a11y), internationalization (i18n), privacy, and security.  Also add a "card" for this issue to the [Strategy Funnel](https://github.com/w3c/strategy/projects/2).

Communities suggested for outreach: 

Known or potential areas of concern: 

Where would charter proponents like to see issues raised? (this strategy funnel issue, a different github repo, email, ...)

Anything else we should think about as we review?

**Comment by himorin** [comment]
diff from current to proposed: https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2F2018%2F11%2Faria-charter&doc2=https%3A%2F%2Fraw.githack.com%2Fw3c%2Faria%2Fcharter-2021%2Fcharter.html

**Comment by himorin** [comment]
No comment/request from i18n.

**Comment by samuelweiler** [comment]
A a naive reader, ARIA's scope and work products are not clear, and I would love to see some rewrites in the introduction and/or scope.  Here are some questions that may help:

"...to address needs reported by authors...": authors of what?  Who are we serving here, and who's input are we listening to?

"...to achieve parity with native host languages...": what is a native host language?  Is there a way to say this in plainer language?  (This term is used at least three times.)

"For each ARIA specification developed by this Working Group, create a corresponding Accessibility API Mappings specification ..."  It seems odd that all specifications developed by the "ARIA WG" are somehow not "ARIA specifications".  Is the term ARIA overloaded here?  Again, is there a way to unpack this for the naive reader?  (e.g. The list of deliverables doesn't seem pairwise matched, as I might expect from the current Scope - I see "Core Accessibility API mappings" with no "Core Accessibility API" "ARIA specification", "Digital Publishing Accessibility API Mappings" with no "Digital Publishing Accessibility API" "ARIA specification".)

How can you write this for a technically sophisticated reader who knows nothing about a11y?


Nit: the Digital Publishing Accessibility API Mappings link is wrong.

I see that most, if not all, if the current ARIA specs do not include the requisite Security and Privacy analyses and write ups. I'm glad to see that the proposed charter requires those.

**Comment by plehegar** [comment]
Should SVG-AAM be added to this charter?

**Comment by michael-n-cooper** [comment]
@plehegar 
> Would https://www.w3.org/TR/using-aria/ fit into this charter since we'd like to close the Web Platform WG finally?

Using ARIA, despite its name, was not produced by the ARIA WG. That document is one source of guidance for ARIA in HTML, also the name of a TR doc, also not produced by the ARIA WG. The HTML-specific aspects of this guidance is beyond the scope of the ARIA WG, and the rest of the guidance is covered in the [WAI-ARIA Authoring Practices](https://w3c.github.io/aria-practices/) which receives a lot of investment in the ARIA WG. I suggest, if the Web Platform WG does not want to maintain that document, it be retired, possibly with a reference to the Practices.

**Comment by michael-n-cooper** [comment]
@samuelweiler 
> As a naive reader, ARIA's scope and work products are not clear, and I would love to see some rewrites in the introduction and/or scope. Here are some questions that may help:
> 
> "...to address needs reported by authors...": authors of what? Who are we serving here, and who's input are we listening to?

I added "of accessible content" to that sentence. It is people making Web content using emerging design patterns that they are not able to make fully accessible, who identify ARIA features that may be needed.
> 
> "...to achieve parity with native host languages...": what is a native host language? Is there a way to say this in plainer language? (This term is used at least three times.)

I added after the first instance (excluding mission at the top) "(markup languages such as HTML or SVG that can use ARIA attributes to provide additional accessibility information)".
> 
> "For each ARIA specification developed by this Working Group, create a corresponding Accessibility API Mappings specification ..." It seems odd that all specifications developed by the "ARIA WG" are somehow not "ARIA specifications". Is the term ARIA overloaded here? 

I don't think all specifications developed by a group need to be named for the group. Accessible Rich Internet Applications Working Group is the most clear description of what the group does.

> Again, is there a way to unpack this for the naive reader? (e.g. The list of deliverables doesn't seem pairwise matched, as I might expect from the current Scope - I see "Core Accessibility API mappings" with no "Core Accessibility API" "ARIA specification", "Digital Publishing Accessibility API Mappings" with no "Digital Publishing Accessibility API" "ARIA specification".)

The answer to this is not concise enough for a charter, and I think is not needed detail. Because we develop on varying timelines, not all specifications are included in this charter. However, I did add DPub ARIA, accompanying DPub-AAM, since the group has resumed work on that recently.

> 
> How can you write this for a technically sophisticated reader who knows nothing about a11y?

In the structure of a charter, I don't think we can.
> 
> Nit: the Digital Publishing Accessibility API Mappings link is wrong.

Fixed.

**Comment by marcoscaceres** [comment]
ReSpec flagged that the Aria specs were using the old W3C Document license. It would be great if we could move Aria WG to use more permissive W3C-software-doc license instead.

**Comment by marcoscaceres** [comment]
No, that’s not true at all @michael-n-cooper. It’s because it’s a better license for everyone and it makes a huge difference to implementers (e.g., being able to copy/paste spec text into C++ code).

**Comment by cookiecrook** [comment]
Apple also prefers the Software and Document license.

**Comment by plehegar** [comment]
https://lists.w3.org/Archives/Member/w3c-ac-members/2022JanMar/0011.html
