### ISSUE TITLE
MGB template 

### ISSUE THREAD

**Issue by MGBtrust** [w3c/strategy#283]
Have a new idea for web standards? Suggest it here with links to resources you'd recommend we use for follow up (technology reports, news articles, suggested contacts)
The ides is to see if these exploratory pointers spark ideas from others or suggest connections to work in progress. 

Include some links here: 
* [link]()

**Comment by Alilux** [comment]
I need help before I import i really believe this is the solution .

**Comment by Alilux** [comment]
https://www.w3.org/Guide/process/charter.html#horizontal-review

**Comment by Alilux** [comment]
http://w3c.github.io/wot/charters/smart-cities/smart-cities-ig-charter.html#coordination

**Comment by wseltzer** [comment]
This appears to be a paste of template text
