### ISSUE TITLE
Graph processing & Querying

### ISSUE THREAD

**Issue by philarcher** [w3c/strategy#29]

**Comment by philarcher1** [comment]
This follows on from the 'fixing SPARQL errata' conversation that's been going on for a while. Axel Polleres and I spoke about a possible workshop on graph querying that might lead to some new work including, but not limited to, fixing those errata. See mail in team archive at https://lists.w3.org/Archives/Team/team-strat/2016Oct/0094.html

**Comment by pchampin** [comment]
This has been taken over by the SPARQL 1.2 Community Group: https://www.w3.org/community/sparql-12/.
