### ISSUE TITLE
Second Screen WG rechartering

### ISSUE THREAD

**Issue by tidoust** [w3c/strategy#291]
Current charter expires at the end of the year (a short extension will most likely be needed while the new charter gets prepared, processed and approved).

- [Proposed charter for 2022-2024](https://w3c.github.io/secondscreen-charter/)
- [HTML diff between the current and proposed charters](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2F2020%2F12%2Fsecond-screen-wg-charter.html&doc2=https%3A%2F%2Fw3c.github.io%2Fsecondscreen-charter%2F)

Where would charter proponents like to see issues raised?
[Second Screen WG Charter repo](https://github.com/w3c/secondscreen-charter)

Anything else we should think about as we review? 
- [Second Screen WG PAG](https://www.w3.org/2021/08/secondscreen-pag/), scoped to patent disclosures and exclusions related to the Open Screen Protocol is ongoing
- Main change, on top of refreshing the boilerplate text, is to add the [Multi-Screen Window Placement API](https://webscreens.github.io/window-placement/) to the WG, after a period of incubation in the Second Screen CG.

**Comment by samuelweiler** [comment]
Filed three issues, none of them blocking, though I wonder if the WG will meet its success criteria with the new Multi-Screen Window Placement API.  See https://github.com/w3c/secondscreen-charter/issues/26.  @pes10k, any thoughts (in that issue)?

Also
https://github.com/w3c/secondscreen-charter/issues/24
https://github.com/w3c/secondscreen-charter/issues/25

**Comment by himorin** [comment]
seems the last two links in history table is wrong (pointing the page itself?).

**Comment by pes10k** [comment]
I second @samuelweiler 's point and concern, that the fingerprinting risk here is very large, and solutions are not obvious.  I would be interested in what the WG has in mind by selecting "unnecessary or severe" as the relevant criteria.

**Comment by himorin** [comment]
No comment/request from i18n.

**Comment by michael-n-cooper** [comment]
APA wants a clarification about the meaning of the term "second screen", following on earlier discussions. @JaninaSajka will provide more detail.

**Comment by tidoust** [comment]
> I second @samuelweiler 's point and concern, that the fingerprinting risk here is very large, and solutions are not obvious. I would be interested in what the WG has in mind by selecting "unnecessary or severe" as the relevant criteria.

@pes10k Could you weigh in https://github.com/w3c/secondscreen-charter/issues/26 if you feel that the documents that the group has prepared do not adequately explain what it has in mind?

**Comment by tidoust** [comment]
> APA wants a clarification about the meaning of the term "second screen", following on earlier discussions. @JaninaSajka will provide more detail.

I'm exchanging with @JaninaSajka via email. Clarification is on whether bluetooth headsets and speakers are included in the notion of "presentation display" (they are) and whether refreshable braille displays are included as well (they may not be depending on their capabilities)

**Comment by michael-n-cooper** [comment]
[head of public thread between @JaninaSajka and @tidoust ](https://lists.w3.org/Archives/Public/public-apa/2021Dec/0009.html)
[APA discussion 8 Dec 2021](https://www.w3.org/2021/12/08-apa-minutes.html#t03)
@JaninaSajka will follow up, with awareness of schedule to go to W3M

**Comment by michael-n-cooper** [comment]
APA is satisfied by discussion closed at https://lists.w3.org/Archives/Public/public-apa/2022Jan/0017.html.

**Comment by plehegar** [comment]
Announced.
