### ISSUE TITLE
Web of Things (WoT) WG Charter Extension via the Rechartering Process

### ISSUE THREAD

**Issue by ashimura** [w3c/strategy#298]
New charter proposal, reviewers please take note.

# Charter Review

[Charter:](https://w3c.github.io/wot/charters/wot-wg-2022-ext.html) https://w3c.github.io/wot/charters/wot-wg-2022-ext.html

What kind of charter is this? Check the relevant box / remove irrelevant branches. 

* Existing 
 - [x] Existing WG recharter 
 - [diff from previous charter](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2F2020%2F01%2Fwot-wg-charter.html&doc2=http%3A%2F%2Fw3c.github.io%2Fwot%2Fcharters%2Fwot-wg-2022-ext.html)

***Note:***
* As shown by the title of this issue and the above diff, this is rather an extension by one year and the difference from the [previous Charter](https://www.w3.org/2020/01/wot-wg-charter.html) is only the start date and the end date.
* Please note that we usually can get a 6-month extension based on the W3M approval. However, this time the WoT WG would like to get a one-year extension to finalized the spec work defined by the [previous Charter](https://www.w3.org/2020/01/wot-wg-charter.html) and the W3M suggested we follow the rechartering procedure for that purpose. So we'd like to start with the horizontal reviews again (followed by the AC review).

***TBD:***
* Horizontal Reviews: apply the Github label "Horizontal review requested" to request reviews for accessibility (a11y), internationalization (i18n), privacy, and security.

Communities suggested for outreach:
* nothing specifically (As mentioned above, this is rather an extension and the WoT WG had collaborative discussion with the WoT IG and already got consensus with them.)

Known or potential areas of concern:
* nothing specifically (As mentioned above, this is rather an extension and there is no changes from the [previous Charter](https://www.w3.org/2020/01/wot-wg-charter.html) other than the start/end dates.

Where would charter proponents like to see issues raised? (this strategy funnel issue, a different github repo, email, ...)
* Please put comments on this issue directly if any

Anything else we should think about as we review? 
* nothing specifically

**Comment by plehegar** [comment]
Note that the proposal here is simply to extend the end date of the Group by one year. No other change (so far) on the charter.

**Comment by himorin** [comment]
(not as i18n HR & just a comment)

Communication section has a text as:

> This group primarily conducts its technical work on GitHub issues using both a master repo and repos specific to each deliverable. 

but a link at `master repo` seems an organization (named as wot) but not repo.

**Comment by ashimura** [comment]
> (not as i18n HR & just a comment)
> 
> Communication section has a text as:
> 
> > This group primarily conducts its technical work on GitHub issues using both a master repo and repos specific to each deliverable.
> 
> but a link at `master repo` seems an organization (named as wot) but not repo.

Sorry but I've just fixed the URL as "https://github.com/w3c/wot" for that link.

Could you please start an actual review now?

**Comment by himorin** [comment]
No comment/request from i18n

**Comment by plehegar** [comment]
This charter needs to switch to Patent Policy 2020.

**Comment by ashimura** [comment]
@himorin , @plehegar and @brewerj , thanks a lot!
@plehegar , the [draft Charter](https://w3c.github.io/wot/charters/wot-wg-2022-ext.html) already refers to the [Patent Policy 2020](https://www.w3.org/Consortium/Patent-Policy-20200915/) :)

**Comment by brewerj** [comment]
Currently the Coordination section includes the following: 

> [Accessible Platform Architectures Working Group](https://www.w3.org/WAI/APA/)
    For coordination on impacts of Web of Things technologies on accessibility to users with disabilities.

To highlight the importance of also harnessing new benefits of web-enabled connectivity, could we expand this description to include: 

> For coordination on impact of WoT technologies on accessibility for users with disabilities, and to support new capabilities that help leverage WoT connectivity and sensor networks for disability support in public and private spaces.

**Comment by mmccool** [comment]
@mmccool and @sebastiankb discussed and the suggested changes to the accessibility text seem appropriate.  Will confirm with the WoT WG today and will ask for a resolution to update the charter.

**Comment by ashimura** [comment]
@wseltzer and @samuelweiler , we'd assume there should not be any (big) problems with security and privacy viewpoints either since [this draft Charter for extension](https://w3c.github.io/wot/charters/wot-wg-2022-ext.html) is basically identical to the [current Charter](https://www.w3.org/2020/01/wot-wg-charter.html).

Can we move forward to the next step?

**Comment by mmccool** [comment]
Update to a11y description done.

**Comment by ashimura** [comment]
> @himorin , @plehegar and @brewerj , thanks a lot! @plehegar , the [draft Charter](https://w3c.github.io/wot/charters/wot-wg-2022-ext.html) already refers to the [Patent Policy 2020](https://www.w3.org/Consortium/Patent-Policy-20200915/) :)

After some more discussion with @plh , I've updated the Patent Policy section based on the [latest Charter template](https://github.com/w3c/charter-drafts/blob/gh-pages/charter-template.html).

**Comment by samuelweiler** [comment]
Some editorial things; my privacy and security reviews are ongoing...

I notice that you're not using the current charter template.  I'm content with the security and privacy text, but I'm calling it out so other reviewers will pay more attention

The link to the WoT IG charter is out of date.  (Also, the old WoT IG charter doesn't include a pointer to the newer one.)

The copyright date has not been updated.

**Comment by mmccool** [comment]
To clarify, this is just an extension, so we are updating the previous charter.  This is why we're not using the new template.  Do we have to use a new template for an extension charter?

**Comment by ashimura** [comment]
> Some editorial things; my privacy and security reviews are ongoing...
> 
> I notice that you're not using the current charter template. I'm content with the security and privacy text, but I'm calling it out so other reviewers will pay more attention
> 
> The link to the WoT IG charter is out of date. (Also, the old WoT IG charter doesn't include a pointer to the newer one.)

The link to the WoT IG has been updated with:
  http://w3c.github.io/wot/charters/wot-wg-2022-ext.html
 
> The copyright date has not been updated.

Also the copyright year has been updated as "2022".

Thanks, @samuelweiler !

**Comment by samuelweiler** [comment]
> To clarify, this is just an extension, so we are updating the previous charter. This is why we're not using the new template. Do we have to use a new template for an extension charter?

Typically, yes.

**Comment by samuelweiler** [comment]
> > The link to the WoT IG charter is out of date. (Also, the old WoT IG charter doesn't include a pointer to the newer one.)
> 
> The link to the WoT IG has been updated with: http://w3c.github.io/wot/charters/wot-wg-2022-ext.html

It looks like you pointed to the IG charter (yay), not the WG charter.

**Comment by ashimura** [comment]
> > > The link to the WoT IG charter is out of date. (Also, the old WoT IG charter doesn't include a pointer to the newer one.)
> > 
> > 
> > The link to the WoT IG has been updated with: http://w3c.github.io/wot/charters/wot-wg-2022-ext.html
> 
> It looks like you pointed to the IG charter (yay), not the WG charter.

Ah, sorry.

I think I meant:
[[
The link to the WoT IG has been updated with: 
  https://www.w3.org/2021/12/wot-ig-2021.html

Please see the updated proposed WG Charter at:
  http://w3c.github.io/wot/charters/wot-wg-2022-ext.html
]]
:)

Sorry again for the confusion.

**Comment by ashimura** [comment]
@plehegar and @swickr , as responded by email, I've updated the [draft Charter](https://w3c.github.io/wot/charters/wot-wg-2022-ext.html) with the publication dates of the previous drafts based on your comments, and now we've got W3M's approval for the AC review.
So I'll work with the MarComm Team for the announcement.
