### ISSUE TITLE
Federated Credential Management

### ISSUE THREAD

**Issue by samuelweiler** [w3c/strategy#299]
https://github.com/fedidcg/FedCM is being incubated in the [FedID CG](https://github.com/fedidcg)

It has extensive community involvement.  It needs broader browser involvement, especially from browsers who have already blocked 3p cookies and have implemented work-arounds to help federated login flows keep working.

**Comment by ianbjacobs** [comment]
One of the co-Chairs of the FedID CG has reached out to me with a link to a [draft WebIdentityCredentials Working Group Charter](https://github.com/fedidcg/fedidcg.github.io/blob/main/charters/Proposed-WG-WebIdentityCredentials.md). 

* FedCM is shipping in Chrome, Edge, Samsung Internet Browser, and Opera (see [caniuse data](https://caniuse.com/mdn-api_federatedcredential)).
* There are statements of initial support [from Mozilla](https://github.com/mozilla/standards-positions/issues/618) and [from Apple](https://lists.webkit.org/pipermail/webkit-dev/2022-March/032162.html)
* The TAG did a [review of FedCM](https://github.com/w3ctag/design-reviews/issues/718) in March 2022 and [largely supported](https://github.com/w3ctag/design-reviews/issues/718#issuecomment-1187725216) the direction of the API, although they would like future opportunities to review it.
