### ISSUE TITLE
Dataset Exchange Working Group Charter 2022

### ISSUE THREAD

**Issue by plehegar** [w3c/strategy#301]
New charter proposal, reviewers please take note.

# Charter Review

[Charter](https://w3c.github.io/dxwg/charter/charter-2022.html)

Updates:
- New charter template
- Switch to Patent Policy 2020
- Refresh timeline for DCAT 3
- Add 2 more years to the Group

What kind of charter is this? Check the relevant box / remove irrelevant branches. 

* Existing 
 - [x] Existing WG recharter 

[diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2F2020%2F02%2Fdx-wg-charter.html&doc2=https%3A%2F%2Fw3c.github.io%2Fdxwg%2Fcharter%2Fcharter-2022.html)

https://github.com/w3c/dxwg/pull/1452

Communities suggested for outreach: 

none

Known or potential areas of concern: 

none

Where would charter proponents like to see issues raised? (this strategy funnel issue, a different github repo, email, ...)

Here or in https://github.com/w3c/dxwg/pull/1452

Anything else we should think about as we review? 

nope

**Comment by plehegar** [comment]
Note that the WG is still hesitant to keep "[Content Negotiation by Profile](https://www.w3.org/TR/dx-prof-conneg/)" on the REC track, due to very minimum progress/interest

**Comment by michael-n-cooper** [comment]
No comments from APA on charter.

**Comment by himorin** [comment]
No comment/request from i18n

**Comment by plehegar** [comment]
@samuelweiler , I plan to request W3M review for this charter. Let me know before if you can security/privacy concerns. There is no change in scope so I'd be surprised if there are issues there.

**Comment by plehegar** [comment]
(updated link to charter and diff since the git branch was merged in https://github.com/w3c/dxwg/pull/1452 )

**Comment by samuelweiler** [comment]
> Note that the WG is still hesitant to keep "[Content Negotiation by Profile](https://www.w3.org/TR/dx-prof-conneg/)" on the REC track, due to very minimum progress/interest

The fingerprinting surface mitigations in [Content Negotiation by Profile](https://www.w3.org/TR/dx-prof-conneg/) are probably not up to current standards.  If work is going to continue, I suggest getting a thorough privacy review before investing a great deal of effort into it.

**Comment by plehegar** [comment]
Charter approved. https://lists.w3.org/Archives/Member/w3c-ac-members/2022AprJun/0061.html
