### ISSUE TITLE
Immersive Web Working Group 2022/Jun recharter

### ISSUE THREAD

**Issue by himorin** [w3c/strategy#302]
New charter proposal, reviewers please take note.

# Charter Review

[Charter:](https://w3c.github.io/immersive-web-wg-charter/immersive-web-wg-charter.html)

[diff from current running](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2F2020%2F05%2Fimmersive-Web-wg-charter.html&doc2=https%3A%2F%2Fw3c.github.io%2Fimmersive-web-wg-charter%2Fimmersive-web-wg-charter.html)

What kind of charter is this? Check the relevant box / remove irrelevant branches. 

* New
 - [ ] New WG 
 - [ ] New IG
 - If this is a new WG or IG charter request, link to [Advance Notice](), and any issue discussion: 

* Existing 
 - [x] Existing WG recharter 
 - [ ] Existing IG recharter
 - If this is a charter extension or revision, link a [diff from previous charter](https://services.w3.org/htmldiff), and any issue discussion:

Horizontal Reviews: apply the Github label "Horizontal review requested" to request reviews for accessibility (a11y), internationalization (i18n), privacy, and security.  Also add a "card" for this issue to the [Strategy Funnel](https://github.com/w3c/strategy/projects/2).

Communities suggested for outreach: nothing

Known or potential areas of concern: nothing

Where would charter proponents like to see issues raised? (this strategy funnel issue, a different github repo, email, ...): [repository for this charter](https://github.com/w3c/immersive-web-wg-charter/issues)

Anything else we should think about as we review? : nothing

**Comment by himorin** [comment]
note: remaining `Patent Disclosures` section will be removed shortly.

**Comment by brewerj** [comment]
In the coordination section, there is a reference to APA WG: 

>  Accessible Platform Architectures (APA) Working Group
    The APA Working Group will review deliverables for accessibility implications and help develop solutions. 

Since we now have a resource that helps id user needs in XR space, I recommend that you add a note linking to XAUR as a resource for ideas about solutions: 

> s/help develop solutions, noting the following [XAUR ](https://www.w3.org/TR/xaur/) resource.

**Comment by michael-n-cooper** [comment]
No comments from APA.

**Comment by himorin** [comment]
updated draft:

- Added mention to XAUR in APA liaison (https://github.com/w3c/immersive-web-wg-charter/pull/52)
- Removed Patent Disclosures section (https://github.com/w3c/immersive-web-wg-charter/pull/51)

**Comment by himorin** [comment]
No comment/request from i18n

**Comment by himorin** [comment]
@pes10k, @samuelweiler could you kindly check this draft per privacy (and security)?

**Comment by samuelweiler** [comment]
No privacy or security comments.  Many of these specs will be "exciting" from a privacy perspective, but the WG has a good history of addressing issues, so I'm not raising any issues with the charter.

I filed three issues re: the history/change log section.

**Comment by himorin** [comment]
https://www.w3.org/2022/07/immersive-web-wg-charter.html
charter out.
