### ISSUE TITLE
WebRTC WG charter 2022

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/strategy#331]
New charter proposal, reviewers please take note.

# Charter Review

[Draft WebRTC WG charter](http://w3c.github.io/webrtc-charter/webrtc-charter.html)

What kind of charter is this? Check the relevant box / remove irrelevant branches. 

* Existing 
 - [x] Existing WG recharter 

Horizontal Reviews: apply the Github label "Horizontal review requested" to request reviews for accessibility (a11y), internationalization (i18n), privacy, and security.  Also add a "card" for this issue to the [Strategy Funnel](https://github.com/w3c/strategy/projects/2).

Communities suggested for outreach: 

Known or potential areas of concern: 

Where would charter proponents like to see issues raised? (this strategy funnel issue, a different github repo, email, ...)
https://github.com/w3c/webrtc-charter/issues

Anything else we should think about as we review?

**Comment by samuelweiler** [comment]
added a card to the pipeline.

**Comment by himorin** [comment]
[htmldiff from current running charter](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2F2020%2F09%2Fwebrtc-charter.html&doc2=https%3A%2F%2Fw3c.github.io%2Fwebrtc-charter%2Fwebrtc-charter.html) shows almost no change, and also WebRTC 1.0 is still listed in [deliverables section](https://w3c.github.io/webrtc-charter/webrtc-charter.html#deliverables) as under development.
Is this version really the final draft for review? Or any PR(s) has not merged yet?

**Comment by dontcallmedom** [comment]
Thanks for the notice!

*  the completion date for WebRTC 1.0 needs an update indeed (since it has now been published as a Rec); that being said, the Working Group does intend to continue publishing updates to the WebRTC Recommendation
* there was one pending pull request listing new deliverables which I've just merged

But otherwise, the charter is purposefully only bringing minimal changes.

**Comment by samuelweiler** [comment]
I would like to get some extra input on this.  If it could wait a couple more weeks, that would be grand.  I filed some purely editorial things.

**Comment by himorin** [comment]
no comment/request from i18n

**Comment by plehegar** [comment]
announced https://lists.w3.org/Archives/Member/w3c-ac-members/2022OctDec/0001.html
