### ISSUE TITLE
[wg/ag] Accessibility Guidelines WG recharter

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/strategy#332]
New charter proposal, reviewers please take note.

# Charter Review

[Charter](https://www.w3.org/2022/06/draft-ag-charter)

What kind of charter is this? Existing WG recharter 

Communities suggested for outreach: 

Known or potential areas of concern: 

Where would charter proponents like to see issues raised? 

[Github PR](https://github.com/w3c/wcag/blob/charter-2022/charter.html)
[Github issue](https://github.com/w3c/wcag/issues)

Anything else we should think about as we review?

**Comment by samuelweiler** [comment]
Added a card to the pipeline.

**Comment by ruoxiran** [comment]
Please add FAST and maturity model to APA liaison, and collaborate on guidelines implications of APA´s AUR documents.

**Comment by svgeesus** [comment]
I see this proposed charter just went to advance notice.

**Comment by svgeesus** [comment]
[Diff wrt charter template](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fw3c.github.io%2Fcharter-drafts%2Fcharter-template.html&doc2=https%3A%2F%2Fwww.w3.org%2F2022%2F06%2Fdraft-ag-charter) looks okay.

Surprised to see the Document rather than the Software and Document license.

**Comment by brewerj** [comment]
@svgeesus Document license continues to be permitted for W3C work when needed. In this case it is needed as it helps with regard to standards harmonization in uptake of accessibility requirements, including when accessibility guidelines are taken up in regulatory settings. Otherwise one can get a rapid proliferation of derivative versions which can lead to fragmentation of requirements in different settings. These can make it more difficult for organizations to conform to accessibility requirements across multiple geographic or jurisdictional settings.

**Comment by samuelweiler** [comment]
I'm surprised by the overall slow timeline, and I encourage thoughtful W3M review of that.

I filed several PRs and issues for ordinary things, none of which are blockers: https://github.com/w3c/wcag/pull/2531 https://github.com/w3c/wcag/pull/2530 https://github.com/w3c/wcag/issues/2527 https://github.com/w3c/wcag/issues/2528 https://github.com/w3c/wcag/issues/2529

I observe that the charter uses the "separate privacy and security sections" language, which we've recently changed in the template, but there's no problem with using this version.

**Comment by himorin** [comment]
no comment/request from i18n

**Comment by plehegar** [comment]
Advance notice sent on [June 16](https://lists.w3.org/Archives/Member/w3c-ac-members/2022AprJun/0057.html).

**Comment by plehegar** [comment]
WCAG 2.2 got shipped today. This charter can now be approved.

**Comment by plehegar** [comment]
Announced: https://lists.w3.org/Archives/Member/w3c-ac-members/2023OctDec/0028.html
