### ISSUE TITLE
WebTransport WG charter 2022

### ISSUE THREAD

**Issue by ylafon** [w3c/strategy#333]
New charter proposal, reviewers please take note.

# Charter Review

[Draft WebTransport WG charter](https://w3c.github.io/charter-drafts/wt-2022.html)

What kind of charter is this? Check the relevant box / remove irrelevant branches. 

* Existing 
 - [X] Existing WG recharter 
 - [diff from previous charter](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2F2020%2F12%2Fwebtransport-wg-charter.html&doc2=https%3A%2F%2Fw3c.github.io%2Fcharter-drafts%2Fwt-2022.html)

Horizontal Reviews: apply the Github label "Horizontal review requested" to request reviews for accessibility (a11y), internationalization (i18n), privacy, and security. **Also add a "card" for this issue to the [Strategy Funnel](https://github.com/w3c/strategy/projects/2).**

Communities suggested for outreach: 

Known or potential areas of concern: 

Where would charter proponents like to see issues raised? (this strategy funnel issue, a different github repo, email, ...)
https://github.com/w3c/charter-drafts with \[wt-2022]

Anything else we should think about as we review? 
Simple charter extension, the WG is close to reach CR.

**Comment by himorin** [comment]
no comment/request from i18n
