### ISSUE TITLE
Service Workers WG charter 2022

### ISSUE THREAD

**Issue by ylafon** [w3c/strategy#334]
New charter proposal, reviewers please take note.

# Charter Review

[Draft Service Workers Charter:](https://w3c.github.io/charter-drafts/sw-2022.html)

What kind of charter is this? Check the relevant box / remove irrelevant branches. 

* Existing 
 - [x] Existing WG recharter 
 - If this is a charter extension or revision, link a [diff from previous charter](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2F2021%2F05%2Fsw-charter.html&doc2=https%3A%2F%2Fw3c.github.io%2Fcharter-drafts%2Fsw-2022.html), and any issue discussion:

Horizontal Reviews: apply the Github label "Horizontal review requested" to request reviews for accessibility (a11y), internationalization (i18n), privacy, and security. **Also add a "card" for this issue to the [Strategy Funnel](https://github.com/w3c/strategy/projects/2).**

Communities suggested for outreach: 

Known or potential areas of concern: 

Where would charter proponents like to see issues raised? (this strategy funnel issue, a different github repo, email, ...)
https://github.com/w3c/charter-drafts with [sw-2022]

Anything else we should think about as we review? 

This is mainly a charter extension for two years of an evergreen document

**Comment by himorin** [comment]
- in history table, latest running charter link points to announcement to ac-members, but better to be replaced with `https://www.w3.org/2021/05/sw-charter`?

**Comment by ylafon** [comment]
Good point, it was a copy/paste of the previous draft charter, and it was already wrong by then.

**Comment by ruoxiran** [comment]
no comment from APA WG.

**Comment by himorin** [comment]
no comment/request from i18n

**Comment by samuelweiler** [comment]
I haven't seen privacy nor security review requests for service workers in recent memory.  What's the planned timeline for requesting those, especially given the move to snapshots?

Also filed: https://github.com/w3c/charter-drafts/issues/402

**Comment by plehegar** [comment]
announced: https://lists.w3.org/Archives/Member/w3c-ac-members/2023JanMar/0028.html
