### ISSUE TITLE
Chinese Web Interest Group Charter 2022

### ISSUE THREAD

**Issue by xfq** [w3c/strategy#336]
New charter proposal, reviewers please take note.

# Charter Review

Charter: https://w3c.github.io/chinese-ig-charter/charter-2022.html

What kind of charter is this? Check the relevant box / remove irrelevant branches. 

 - [x] Existing IG recharter

Horizontal Reviews: apply the Github label "Horizontal review requested" to request reviews for accessibility (a11y), internationalization (i18n), privacy, and security. **Also add a "card" for this issue to the [Strategy Funnel](https://github.com/w3c/strategy/projects/2).**

Communities suggested for outreach: 

Known or potential areas of concern: 

Where would charter proponents like to see issues raised? https://github.com/w3c/chinese-ig-charter

Anything else we should think about as we review? 

This is mainly a charter extension for two years without changing the group's scope.

**Comment by ruoxiran** [comment]
Looks good to APA WG.

**Comment by himorin** [comment]
no comment/request from i18n

**Comment by samuelweiler** [comment]
[Diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2F2020%2F10%2Fchinese-web-ig-charter.html&doc2=https%3A%2F%2Fw3c.github.io%2Fchinese-ig-charter%2Fcharter-2022.html)

No comments re: security nor privacy.

**Comment by xfq** [comment]
Announced: https://lists.w3.org/Archives/Public/public-chinese-web/2022Nov/0000.html
