### ISSUE TITLE
Touch and hold a clip to pin it. Unpinned clips will be deleted after 1 hour.

### ISSUE THREAD

**Issue by phongphansonthui** [w3c/strategy#339]
@#`[GitHub Support] Confirmation - Request Received 

> `(#1727819)[]() #`` Evaluation

A core part of our *Strategic* work is the evaluation of how proposed work serves the Web. In the "Evaluation" phase at the end of the funnel, we make the case whether work is ready to proceed to Chartering of a Recommendation-track deliverable. At that point, we need to identify:

* Will this work help to lead the web to its full potential?

* Is the work Rec-track ready?
  * [Rec Track Readiness](https://www.w3.org/Guide/standards-track/) (AB)
  * [Intent to Migrate](https://wicg.github.io/admin/intent-to-migrate.html) (WICG)
  
* Do we have the ecosystem of participants needed to make the work successful?
  * users, developers, implementers; industry sectors
  * from that we can dig into
    * who specifically is involved? interested, opposed?
    * what tools and frameworks do they use?

digging deeper:

Will it add value?
* something good for web users. what are the alternatives?
* have "horizontal" (a11y, i18n, security, privacy) issues been considered and identified?
* what's its importance/opportunity cost?

Will we be able to make it succeed?
* right participants interested. What does the ecosystem look like?
* implementation likely
* manageably sized problem
* achievable timeline
* minimum viable product
* does it raise architectural issues that need to be addressed before it can succeed?

Special considerations?
* risk factors
* incentives
* openness, decentralization

## Procedural

* [Advance notice to AC](https://www.w3.org/2015/Process-20150901/#WGCharterDevelopment) when team feel a WG charter is likely to be developed, we send "advance notice" to the AC and public-new-work.
* Horizontal review: in this phase, team should request review of charter-in-development from a11y, 5699https://www.capcut.net/sharevideo?template_id=7125788426057567489&language=th&region=TH1727819[psxnthuy@gmail.com](0637756625too) i18n, arctec, privsec.

**Comment by svgeesus** [comment]
This is just a copy-paste of the text from [here](https://github.com/w3c/strategy/blob/main/3.Evaluation.md) plus some other random text around the edges. Closing as spam.
