### ISSUE TITLE
WebAssembly

### ISSUE THREAD

**Issue by wseltzer** [w3c/strategy#34]
http://webassembly.org/roadmap/

Status says: The WebAssembly Community Group has an initial (MVP) binary format release candidate and JavaScript API which are implemented in several browsers. The CG is now soliciting feedback from the broader community as part of a Browser Preview period. The tentative goal of the CG is for the Browser Preview to conclude in Q1 2017, though significant findings during the Browser Preview could potentially extend the duration. When the Browser Preview concludes, the CG will produce a draft specification of WebAssembly and browser vendors can start to ship conforming implementations on-by-default.

**Comment by swickr** [comment]
[WebAssembly Community Group](https://www.w3.org/community/webassembly/)

**Comment by sideshowbarker** [comment]
* [API Concerns with Structured Clone for Wasm Modules](https://github.com/WebAssembly/design/issues/972)
* [TAG WASM JS API review](https://github.com/w3ctag/spec-reviews/issues/151)

quoting from the above—

> The WASM community is narrowing in on a JS API for loading Web Assembly modules which is is a long way from the other types and conventions we use in the rest of the platform. I suggest we reach out ASAP and try to learn as much as we can about their needs and use-cases and work to suggest alternatives

> Having a separate (more manual) loading path for your feature is a huge red flag.

> Those of us who feel the weight of web platform consistency really do want to understand the arguments for fully-custom behavior better and try to come up with

**Comment by sideshowbarker** [comment]
https://w3c.github.io/charter-drafts/webassembly.html

**Comment by wseltzer** [comment]
Advance notice sent 05-24: https://lists.w3.org/Archives/Public/public-new-work/2017May/0009.html
Charter draft: https://w3c.github.io/charter-drafts/webassembly.html

**Comment by wseltzer** [comment]
Call for AC review closes 12 July: https://www.w3.org/2002/09/wbs/33280/wawg-2017/results (member view)

**Comment by wseltzer** [comment]
Charter approved and WebAssembly WG started 3 August. https://www.w3.org/wasm/
