### ISSUE TITLE
Permissions workshop 2022

### ISSUE THREAD

**Issue by samuelweiler** [w3c/strategy#348]
Planning a workshop building on the [2018 permissions workshop](https://github.com/w3c/strategy/issues/78):

Draft CFP in the next comment, so this can be used for current status.

**Comment by samuelweiler** [comment]
draft CFP for horizontal review:


This workshop will bring together UI/UX researchers, browser vendors, OS vendors, and API authors to address challenges presented by more powerful capabilities made available to web applications.

Scope

Our proposed scope includes:

- better alignment of permission lifetime/duration with user tasks;
- human-centric grouping/categorization of permissions and applications;
- challenges with novel capabilities;
- scoping of permissions to origins vs. applications, relation to same origin policy;
- UIs and controls;
- integrated permission control surfaces tailored to the capability itself; and
- permission transparency and control.

We would like to focus on usable security topics and thus propose to explicitly leave advertising-related aspects out of scope. While there is some overlap, we believe this topic area is expansive and would like the outcome of this workshop to provide practical next steps related to permissions.

Dates / venue / host

December 5–6, 2022

- Alternate dates November 14–15

This workshop will be hybrid. 

- In-person at Google Munich, Germany. 
- Remotely, favouring EMEA time zones.

Organising & program committee

- Redacted for now.

Expected attendees
We are planning for 25–35 attendees, subject to host and COVID constraints.

**Comment by himorin** [comment]
no comment and suggestion from i18n

**Comment by samuelweiler** [comment]
@michael-n-cooper any comments?

**Comment by michael-n-cooper** [comment]
@samuelweiler Judy has asked APA not to look at workshops for horizontal review, so I wasn't seeing this. I don't have any comments to offer on this early draft. It's possible accessibility would have use cases for this, but I'm not clear of the scope yet. I'd be surprised if we could pull together a meaningful submission on the time frame though.

**Comment by wseltzer** [comment]
Planned: https://www.w3.org/Privacy/permissions-ws-2022/

**Comment by plehegar** [comment]
[Report](https://www.w3.org/Privacy/permissions-ws-2022/report)
