### ISSUE TITLE
Browsers and the Web of Things

### ISSUE THREAD

**Issue by draggett** [w3c/strategy#35]
Web browsers can be used to provide user interfaces for services for the Web of Things. This can be implemented using JavaScript and the browser supported protocols (HTTP, WebSockets, WebRTC). There is a further opportunity for using Web browsers for installing apps onto your smart home hub when visiting a vendor's website. This raises challenges around how the browser identifies the home hub, and gets the user's permission for installing the app, along with the associated security and privacy concerns. I am expecting home hubs that support apps written in JavaScript, and this raises opportunities for re-use of browser APIs on home hubs.  This will require incubation, but a first step could be a workshop that looks at web of things related work across different groups as well as the expected need for new standards. A workshop would bring together people from different communities and help prepare the ground for further collaboration.

**Comment by svgeesus** [comment]
No traction, no specific proposal. Re-open if that changes.
