### ISSUE TITLE
Recharter of the GPU for the Web Working Group

### ISSUE THREAD

**Issue by tidoust** [w3c/strategy#352]
New charter proposal, reviewers please take note.

# Charter Review

[Draft GPU for the Web Working Group charter](https://gpuweb.github.io/admin/wg-charter.html)

This is a recharter of an existing working group. See the [diff with the current charter](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2F2020%2F12%2Fgpu-wg-charter.html&doc2=https%3A%2F%2Fgpuweb.github.io%2Fadmin%2Fwg-charter.html). Most of the diffs are the result of aligning the contents of the charter with the latest revision of the working group charter template.

No change in scope for now. Further adjustments to the description of the WebGPU Shading Language are still being discussed, which could potentially end up affecting the description of that deliverable in the Scope section.

## Where would charter proponents like to see issues raised?
Issues on the [`gpuweb/admin`](https://github.com/gpuweb/admin/issues) repo prefixed with `[WG charter]` would be great. Feedback on this strategy funnel issue would work too as a fallback.

**Comment by ruoxiran** [comment]
no comment from APA.

**Comment by himorin** [comment]
no comment and suggestion from i18n

**Comment by tidoust** [comment]
> No change in scope for now. Further adjustments to the description of the WebGPU Shading Language are still being discussed, which could potentially end up affecting the description of that deliverable in the Scope section.

The description of the WebGPU Shading Language was clarified in the deliverables section to say that the goal is that the language can be translated into the shading languages of the system APIs WebGPU is implemented upon. No changes were made to the Scope section.

**Comment by samuelweiler** [comment]
No comments re: privacy nor security.

**Comment by tidoust** [comment]
Rechartering done in November 2022, see [new charter](https://www.w3.org/2022/11/gpuweb-charter.html)

**Comment by plehegar** [comment]
Announced: https://lists.w3.org/Archives/Member/w3c-ac-members/2022OctDec/0037.html
