### ISSUE TITLE
Digital Receipts

### ISSUE THREAD

**Issue by draggett** [w3c/strategy#36]
The Web Payments Working Group is focusing on the payment transaction. There is an opportunity for future work on the commercial transaction of which the payment is just a part. When you use a credit card in a brick and mortar store, you are given the credit card transaction receipt and a receipt that lists what you purchased along with the associated terms and conditions. This is what you need to keep if you want to return the goods. There is an opportunity for work on standards for digital receipts that can be issued electronically at the time of purchase. One use case is when are checking out at a store and you are required to provide a receipt to prove that you purchased an item, that you are carrying, in another store. Another use case is to enable third party applications to have access to the digital receipts for your purchases, e.g. to provide categorised summaries on a monthly basis. One idea is to use annotated HTML to enable machine interpretation whilst giving the issuer control over the branding and look of the receipt.

This is related to other opportunities on loyalty schemes, discount coupons, and prepaid vouchers, tickets for events (e.g. concerts) and even for metropolitan transportation.  A common thread is the idea of a digital wallet with open standards for data formats and APIs.  This work could be picked up by the Web Payments Interest Group, but a good first step could be a W3C workshop  to bring together a broad range of stakeholders to discuss the opportunities and see if there is sufficient interest to take these ideas further.

**Comment by ianbjacobs** [comment]
Hi Dave,

In the case of Web payments and application of digital offers, W3C has a chance to improve the user experience.

In the case of digital receipts, there are already industry standards for receipt formats so I don't think we will add value there.

What user experience can we improve?
If the Web cannot already improve the experience, what piece of the stack is missing?
What role would browsers play?

Ian

**Comment by svgeesus** [comment]
Closing as there seems litle W3C can add here
