### ISSUE TITLE
Solid Working Group

### ISSUE THREAD

**Issue by pchampin** [w3c/strategy#360]
The [Solid Community Group] has been created in 2018 to incubate [a set of specifications] based on Tim Berner's Lee project [Solid]. The goal is to propose a new way to build Web applications where data is not centralized in application provider's silos, but kept under the control of the end users.

According to [an email] sent yesterday to the CG, Tim wishes to move some of these specifications to standard track, through the creation of a W3C working group.

I am in contact with a number of people in the CG, and I am happy to folllow this.

[Solid Community Group]: https://www.w3.org/community/solid/
[a set of specifications]: https://solidproject.org/TR/
[Solid]: https://solidproject.org/
[an email]: https://lists.w3.org/Archives/Public/public-solid/2022Nov/0001.html

**Comment by pchampin** [comment]
@plehegar  admin question: would there be a problem if the newly created WG has the same name as the existing CG?

**Comment by charlestonxorg** [comment]
Interesting

**Comment by pchampin** [comment]
formal charter proposal at #377
