### ISSUE TITLE
Media Working Group Rechartering

### ISSUE THREAD

**Issue by tidoust** [w3c/strategy#369]
New charter proposal, reviewers please take note.

# Charter Review

[Charter: Media Working Group](https://w3c.github.io/charter-media-wg/)

This is a recharter for the [existing Media Working Group](https://www.w3.org/media-wg/).

A [diff from previous charter](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2F2021%2F07%2Fmedia-wg-charter.html&doc2=https%3A%2F%2Fw3c.github.io%2Fcharter-media-wg%2F) is available. No change of scope for now. Current draft charter is mostly a refresh to incorporate latest template changes.

Known or potential areas of concern: The working group is discussing what to do with deliverables that did not make progress during the last chartering period.

Where would charter proponents like to see issues raised? In a [dedicated repository](https://github.com/w3c/charter-media-wg/)

<del>The draft charter is not yet ready for horizontal reviews.</del>

**Comment by tidoust** [comment]
The Media WG is still reviewing possible updates to the draft charter, but I don't anticipate major changes and believe it is now "ready enough" for horizontal reviews. No scope change in the current draft charter. Main changes to other sections are:

- The group recently adopted the Audio Session, which was listed under its list of potential normative deliverables in the current group charter. The specification is now listed in the main list of deliverables.
- The group continues to develop a number of registries and related specs. On top of refreshing the list, the draft charter now details them in a separate "Registries" section.
- The group no longer plans to work on an API for find duplicate sessions in EME. Mention of it was dropped from the draft charter accordingly. Work on EME remains scoped to maintenance and the features explicitly mentioned in the draft charter, namely HDCP detection and Encryption Scheme Capability Detection.
- The group no longer plans to take up the work on the Sourcing In-band Media Resource Tracks from Media Containers into HTML CG report. This possibility was dropped from the draft charter.

The group plans to publish a FPWD of EME by the end of this chartering period. If that does not happen in time, the draft charter will be updated to add a Q2 2023 milestone for publication as FPWD.

**Comment by ruoxiran** [comment]
APA WG satisfied with this Charter, thanks.

**Comment by himorin** [comment]
No comment nor request from i18n

**Comment by plehegar** [comment]
Announced https://lists.w3.org/Archives/Member/w3c-ac-members/2023AprJun/0060.html
