### ISSUE TITLE
Web Security IG

### ISSUE THREAD

**Issue by samweiler** [w3c/strategy#37]
Rechartering WebSec IG.  Charter expired in June 2016.  Planning to recharter for two years, adding two additional co-chairs.

**Comment by wseltzer** [comment]
https://w3c.github.io/charter-drafts/websec-ig.html 
sent to IG 7 Nov

**Comment by samweiler** [comment]
Sent to AC 30 Nov 2016  https://lists.w3.org/Archives/Member/w3c-ac-members/2016OctDec/0049.html

**Comment by wseltzer** [comment]
And to IG: https://lists.w3.org/Archives/Public/public-web-security/2016Dec/0001.html
member-visible results-tracking: https://www.w3.org/2002/09/wbs/33280/websec-ig-2016/results

**Comment by wseltzer** [comment]
Review closed 6 Jan with 29 supporters.

**Comment by wseltzer** [comment]
Chartered.
