### ISSUE TITLE
Proposed charter: Publishing Maintenance Working Group

### ISSUE THREAD

**Issue by iherman** [w3c/strategy#374]
New charter proposal, reviewers please take note.

# Charter Review

[Charter: Publishing Maintenance Working Group Charter](https://w3c.github.io/publ-maintenance-wg-charter/)

What kind of charter is this? Check the relevant box / remove irrelevant branches. 

 - [X] New WG 
 - If this is a new WG or IG charter request, link to [Advance Notice](), and any issue discussion: 

- No advance notice sent to the AC yet. AFAIK, only the comm team is allowed to send such a call... I will contact them.

Horizontal Reviews: apply the Github label "Horizontal review requested" to request reviews for accessibility (a11y), internationalization (i18n), privacy, and security. **Also add a "card" for this issue to the [Strategy Funnel](https://github.com/w3c/strategy/projects/2).**

Communities suggested for outreach: 

- Current members of the Publishing and the EPUB Working Group. I will send them a mail after having raised this issue.

Known or potential areas of concern: 

Where would charter proponents like to see issues raised? (this strategy funnel issue, a different github repo, email, ...)

- https://github.com/w3c/publ-maintenance-wg-charter/issues
- https://github.com/w3c/publ-maintenance-wg-charter/pulls

Anything else we should think about as we review? 

As the introduction says, it is "only" a maintenance Working Group, the only special feature that it would pull together the maintenance of the output of _two_ working groups into one place.

**Comment by iherman** [comment]
Groups have been contacted:

- https://lists.w3.org/Archives/Public/public-epub-wg/2023Mar/0002.html a.k.a. as
- https://lists.w3.org/Archives/Public/public-publ-wg/2023Mar/

Covering the two WG-s that are planned to be replaced by this Maintenance WG

**Comment by himorin** [comment]
i18n runs language enablement activities, in coordination with groups of experts over languages, and could find emerging requests to fill gaps to requirements of languages. To where we should contact on such case?

**Comment by iherman** [comment]
@himorin in the hope that I understand your question: the W3C Publishing Activity has three "pillars". The Publishing Business and Community groups, and the active WG (today the EPUB, tomorrow the proposed Maintenance WG). So the target of your contact will depend on the nature of your problem, ranging from general usage/business issues, some general technical issues, down to specific issues with our published standards or notes.

Does this answer your question? First of all, did I understand your question properly?

cc @TzviyaSiegman and @swickr (as publishing co-champions of the activity)

**Comment by iherman** [comment]
cc @wareid @dauwhe @shiestyle (proposed chairs for this Working Group)

**Comment by ruoxiran** [comment]
looks good to APA WG.

**Comment by plehegar** [comment]
EPub charter expires in August, as well as AudioBooks.

Waiting on EPub Proposed Recommendation or REC to start AC Review for this charter.

**Comment by iherman** [comment]
AC review started: https://www.w3.org/2002/09/wbs/33280/pmwg/results

**Comment by iherman** [comment]
AC review ended: https://www.w3.org/2002/09/wbs/33280/pmwg/results, with positive results; charter approval has been submitted to TILT: https://github.com/w3c/tilt-private/issues/9

**Comment by iherman** [comment]
WG announced on the 20 June 2023
