### ISSUE TITLE
Revise Web Payments WG charter to restore some text

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/strategy#379]
Draft charter
  https://www.w3.org/Payments/WG/charter-2023.html

This proposed charter restores a paragraph of text previously in the charter. The following timeline helps to explain this change:

* December 2019: W3C enacts a charter [1] for the Web Payments WG that includes the following text:

  "User interface specifics are out of scope; this Working Group is chartered to Recommend programming interfaces, not user interface specifics. However, it is in scope for the Working Group to discuss user experience, for example as part of understanding user journeys during a checkout experience."

* August 2021: W3C publishes the First Public Working Draft of Secure Payment Confirmation (SPC) [2].
  
* November 2022: W3C enacts an updated charter [3] for the Working Group that does not include the above text. It was removed from the charter to avoid confusion about the group's work on Secure Payment Confirmation, which describes functionality related to the user experience of confirming a transaction.

* March 2023: The Working Group receives a request [4] to restore the text to the charter.

Although the group's chartered end date is 31 December 2024, the proposal is to renew the charter now to facilitate participation in the group. In addition, this charter revision includes updated milestone expectations regarding the publication of the SPC Candidate Recommendation and eventual Recommendation; see the full diff [5].
  
[1] https://www.w3.org/Payments/WG/charter-201912.html
[2] https://www.w3.org/blog/news/archives/9243
[3] https://www.w3.org/Payments/WG/charter-2022.html
[4] https://github.com/w3c/webpayments/issues/262
[5] http://w3.org/brief/NTI1

**Comment by plehegar** [comment]
Advance notice: https://lists.w3.org/Archives/Member/w3c-ac-members/2023AprJun/0014.html

**Comment by ruoxiran** [comment]
https://github.com/w3c/apa/issues/323

**Comment by himorin** [comment]
No comment nor request from i18n

**Comment by ruoxiran** [comment]
APA is OK with this charter.

**Comment by plehegar** [comment]
No concern from privacy folks

**Comment by plehegar** [comment]
I believe this can be closed. Charter got approved and announced.
