### ISSUE TITLE
WebAuthn vNext

### ISSUE THREAD

**Issue by wseltzer** [w3c/strategy#38]
Where do we focus when WebAuthn goes to Rec?

**Comment by samuelweiler** [comment]
Draft charter for WebAuthn includes a v2; expected to go to W3M this week, AC review soon

**Comment by samuelweiler** [comment]
Rechartering completed, anticipating a longer time horizon to finish this work than originally planned.   https://lists.w3.org/Archives/Public/public-webauthn/2017Oct/0138.html

The question of "what next" remains on-point,  but it applies to much ongoing work, so I'm going to mark this issue as completed (for now).

**Comment by samuelweiler** [comment]
Reopening since the current charter expires on 15 Sept 2019.

**Comment by samuelweiler** [comment]
Link to current charter draft?

**Comment by wseltzer** [comment]
Expecting a modest revision to https://www.w3.org/2017/08/web-authentication-charter.html

**Comment by r12a** [comment]
What page should we do HR on?

**Comment by wseltzer** [comment]
Here's the new proposed charter for horizontal review: 
https://www.w3.org/2019/08/web-authentication-charter.html

**Comment by r12a** [comment]
Other than the hope that use cases and examples will include an international selection of subjects, i don't have any specific comments. Waiting for others in i18n to review...

**Comment by brewerj** [comment]
In 3.2 of the charter, following "Use case and requirement documents," please add "including use cases as needed to inform user requirement across horizontal areas."

**Comment by plehegar** [comment]
Announced.
