### ISSUE TITLE
WCAG Charter Update (Silver)

### ISSUE THREAD

**Issue by wseltzer** [w3c/strategy#4]
_From @tidoust on October 12, 2016 7:3_

null

_Copied from original issue: tidoust/strategy#10_

**Comment by svgeesus** [comment]
After discussion with Wendy just now, Core label removed.

**Comment by wseltzer** [comment]
Prepping for AC review

**Comment by wseltzer** [comment]
=> Chartering
AC review started: https://lists.w3.org/Archives/Public/public-new-work/2016Nov/0001.html
member-visible results: https://www.w3.org/2002/09/wbs/33280/accessibility-guidelines-2016/results

**Comment by brewerj** [comment]
Review period closes Friday December 2nd. Monitoring review comments. Discussions with commenters on some issues. Completing reminder pings.

**Comment by wseltzer** [comment]
Discussion of review comments on the member list https://lists.w3.org/Archives/Member/member-agwg-review/

**Comment by wseltzer** [comment]
Chartered.
