### ISSUE TITLE
Music Notation

### ISSUE THREAD

**Issue by iherman** [w3c/strategy#40]
There is a [community group](https://www.w3.org/community/music-notation/):

> The Music Notation Community Group develops and maintains format and language specifications for notated music used by web, desktop, and mobile applications. The group aims to serve a broad range of users engaging in music-related activities involving notation, and will document these use cases.
>
> The initial task of the Community Group is to maintain and update the MusicXML and SMuFL (Standard Music Font Layout) specifications. The goals are to evolve the specifications to handle new use cases and technologies, including greater use of music notation on the web, while maximizing the existing investment in implementations of the existing MusicXML 3.0 and SMuFL specifications.

They _may_ come back to us at some point to try to get this notation through a WG

**Comment by svgeesus** [comment]
MNX first draft posted, 20 March 2017
https://w3c.github.io/mnx/overview/

**Comment by wseltzer** [comment]
Recently published some CG drafts, happy with CG process.

**Comment by svgeesus** [comment]
No real activity since 2017, closing. We can re-open if something new turns up in the area.
