### ISSUE TITLE
Real Estate Interest Group 

### ISSUE THREAD

**Issue by JAlanBird** [w3c/strategy#413]
# Evaluation

The real estate industry is fragmented.  Home buying is the american dream but if you have a disability and / or language barrier the disadvantages are huge. 
In real estate you have three controlling divisions:

1. Large brokerages such as REMAX, Berkshire Hathaway etc.  
2. Large portals such as, Zillow, Inc., CoStar  and Realtor.com 
3. MLS data systems such as Paragon and FlexMLS etc. 

**Large  Brokerages** are very focused on DEI/ADA initiatives and having an interest group at the W3C would help them come together in collaboration of each corporate technology initiatives for web accessibility in the real estate space. Head of the DEI initiatives for the large brokerages are mostly if not all women of diverse backgrounds. Each brokerage has internal committees. 

**Large Portals**  DEI/ADA initiatives or Zillow, CoStar and Realtor.com are “light” at best. They will publish articles but are not as active in the solution space like the brokerages. 

**MLS data systems** are the data for the real estate industry’s listings. These companies implement technology that they feel will increase their revenue. DEI/ADA is not of their concern.  They do what the Brokerage and Zillow will pay for to increase their revenue. 

Brokerages have extensive technology teams continually working on solutions that move their brands forward. A collaboration with the W3C is valuable to both parties because these Brokerages can shed light on data and trends that will help the W3C build out its vision and initiatives.  W3C can bring knowledge, protocols and guidelines that ensure the long-term growth of the Web in regards to real estate. All brokerages have problems that need to be standardized. This interest group helps them get in step with the W3C vision on standardizing in the real estate technology space. 

With the participation of the Brokerages in an interest group, the large portals and MLS’s will follow. 

The Brokerages are focusing on immersive web technology that would be a good alignment with the W3C immersive web working group. 
 
This opportunity was brought to us by Kathleen Lappe who is a new Member with OpenDirect.  You can read her full story about this work at https://docs.google.com/document/d/13hiGKyVOuswVCK4jtb3N9flA72j7Eu-SchwSgX9wIdM/edit?usp=sharing

We have developed a Draft Charter which is located at https://www.w3.org/2023/06/realestate-ig-charter.html 

## Procedural

* [Advance notice to AC](https://www.w3.org/2015/Process-20150901/#WGCharterDevelopment) when team feel a WG charter is likely to be developed, we send "advance notice" to the AC and public-new-work.
* Horizontal review: in this phase, team should request review of charter-in-development from a11y, i18n, arctec, privsec.

**Comment by ianbjacobs** [comment]
Hi @JAlanBird,

Reviewing the draft charter:

* Please break up the mission statement into multiple sentences.
* Please change any instance second person language ("you have") to third person language.
* The phrase "Home buying is global dream of many" needs grammatical work.
* I believe "ADA" is a US-based acronym. Instead I recommend referring in some other way to a focus on accessibility needs.
* I suggest removing all company names from the charter.
* Please fix grammar of "would help them come together in collaboration of each corporate technology initiatives"
* This statement is not appropriate for a charter: Head of the DEI initiatives for the large brokerages are mostly if not all women of diverse backgrounds.
* This statement is not appropriate for a charter: DEI/ADA is not a signifcant concern beyond supporting their client needs (large portals and brokerages). 
* This is not useful in a charter: "With the participation of the Brokerages in an interest group, the large portals and MLS’s will follow."
* This is not useful: "All brokerages have problems that need to be standardized. ". Instead tell me what the problems are that require standardization.

The entire charter needs to be reviewed for grammatical issues.

**Comment by plehegar** [comment]
update: best is to start with a community group to get the real estate community going. Goal is to build momentum to have a successful meeting at TPAC 2024.

Closing for now but feel free to re-open if needed.
