### ISSUE TITLE
[wg/das] Device and Sensors WG 2023 Rechartering

### ISSUE THREAD

**Issue by himorin** [w3c/strategy#429]
New charter proposal, reviewers please take note.

# Charter Review

[Proposed Draft Charter: https://w3c.github.io/charter-drafts/2023/das-wg-charter.html](https://w3c.github.io/charter-drafts/2023/das-wg-charter.html)

What kind of charter is this? Check the relevant box / remove irrelevant branches. 

- [x] Existing WG recharter 

[diff from previous charter](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2F2022%2F11%2Fdas-wg-charter.html&doc2=https://w3c.github.io/charter-drafts/2023/das-wg-charter.html), and any issue discussion:

- Marked several specifications as joint deliverables with WebApps WG

Horizontal Reviews: apply the Github label "Horizontal review requested" to request reviews for accessibility (a11y), internationalization (i18n), privacy, and security. **Also add a "card" for this issue to the [Strategy Funnel](https://github.com/w3c/strategy/projects/2).**

Communities suggested for outreach: @himorin 

Known or potential areas of concern: None

Where would charter proponents like to see issues raised? this strategy funnel issue

Anything else we should think about as we review? 

- <del>one PR (updating /TR/ links, timelines) raised against draft: https://github.com/w3c/das-charter/pull/130</del> (merged)

cc  @anssiko @reillyeon

**Comment by plehegar** [comment]
Added as a [potential PING item](https://www.w3.org/events/meetings/b2a17bf7-f588-4763-b68c-b41a4b05cbc5/20231005T120000/) for October 5.

**Comment by himorin** [comment]
no needs-resolution from i18n, but we would recommend to update sections from 3. Success Criteria to 9. Licensing to align with the latest charter template, especially to remove horizontal review on performance.

**Comment by npdoty** [comment]
"monitoring" may be the wrong framing for privacy-preserving APIs on the Web: the goal of the platform should not be to monitor users' devices, but to allow users who want to to access certain capabilities.

Maybe:
"providing" location information, and not necessarily location information of the hosting device.
"accessing nearby devices without physical contact"
"responding to ambient light levels"
"reacting to changes in motion or orientation"

Defining these specifically as properties of the hosting device or as ongoing monitoring will overconstrain the designed solution in ways that don't align well with privacy.

**Comment by npdoty** [comment]
If the plan is to coordinate with the Web Apps Working Group on the location deliverables (and other deliverables), then the charter should say so directly.

**Comment by reillyeon** [comment]
> If the plan is to coordinate with the Web Apps Working Group on the location deliverables (and other deliverables), then the charter should say so directly.

Does it not? Are you thinking of some language more explicit than, "This work is a joint deliverable with the Web Applications Working Group"?

**Comment by npdoty** [comment]
The [Coordination section](https://w3c.github.io/das-charter/das-wg-charter.html#coordination) indicates that the Web Apps group works on File and Web Manifest and that will be a point of coordination. So maybe you could just add to that section that the plan is also to coordinate with Web Apps on geolocation (either just Geolocation API, or maybe geolocation and motion more generally).

**Comment by npdoty** [comment]
Also, the charter table of contents uses inconsistent labeling on dependencies vs coordination.

**Comment by JaninaSajka** [comment]
APA has no accessibility concerns with the proposed Charter, but wish to ask whether there might be scope to update the Vibration API to support high-fidelity haptics. We inquire because we were presented [Use Cases Requiring High-Fidelity Haptics](https://www.w3.org/2023/09/14-apa-minutes.html#t01) during TPAC 2023.

**Comment by svgeesus** [comment]
I found it odd that System Wake Lock API  is listed twice, with different adopted drafts. That might merit an explanatory note.

**Comment by svgeesus** [comment]
I agree with @npdoty that 'monitor' sounds more like tracking and less like a desirable thing for the user. Suggest presenting a user-centered use case, such as "ambient light sensor enables automatic adjustment of HDR videos and images to maintain viewability in different environments"

**Comment by siusin** [comment]
In 4.1, perhaps we should mention the DAS WG will collaborate with the [Web Applications Working Group](https://www.w3.org/groups/wg/webapps) on a few joint deliverables, including the Contact Picker API, the Screen Wake Lock API, the DeviceOrientation Event Specification and the Geolocation API.

**Comment by himorin** [comment]
draft copied to https://github.com/w3c/charter-drafts/blob/gh-pages/2023/das-wg-charter.html, all PR at das-charter repo merged.

**Comment by himorin** [comment]
> I found it odd that System Wake Lock API is listed twice, with different adopted drafts. That might merit an explanatory note.

I believe these are "[Screen Wake Lock API](https://www.w3.org/TR/wake-lock/)" and "System Wake Lock API"...

**Comment by himorin** [comment]
@plehegar , all: PR for provided comments raised at https://github.com/w3c/charter-drafts/pull/465

**Comment by plehegar** [comment]
"discretion of the Chairs or the Director." s/or the Director//

**Comment by plehegar** [comment]
AC review: https://lists.w3.org/Archives/Member/w3c-ac-members/2023OctDec/0032.html

**Comment by plehegar** [comment]
https://github.com/w3c/charter-drafts/issues/476

**Comment by himorin** [comment]
[email on proposed changed text out to reviewers](https://lists.w3.org/Archives/Member/member-charters-review/2024Jan/0002.html)

**Comment by himorin** [comment]
> [email on proposed changed text out to reviewers](https://lists.w3.org/Archives/Member/member-charters-review/2024Jan/0002.html)

received [one comment](https://lists.w3.org/Archives/Member/member-charters-review/2024Jan/0006.html) on itemized text in Scope.

**Comment by npdoty** [comment]
> > [email on proposed changed text out to reviewers](https://lists.w3.org/Archives/Member/member-charters-review/2024Jan/0002.html)
> 
> received [one comment](https://lists.w3.org/Archives/Member/member-charters-review/2024Jan/0006.html) on itemized text in Scope.

Proposed small change looks good to me.

**Comment by himorin** [comment]
no other comment provided during 7 days review period.

@npdoty @svgeesus I've opened a PR for this change as https://github.com/w3c/charter-drafts/pull/480

**Comment by himorin** [comment]
charter out, and [announced](https://lists.w3.org/Archives/Public/public-device-apis/2024Feb/0006.html)
