### ISSUE TITLE
[ig/web-networks] Web & Networks Interest Group rechartering

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/strategy#433]
New charter proposal, reviewers please take note.

# Charter Review

[Charter:](https://w3c.github.io/web-networks-charter/)

What kind of charter is this? Check the relevant box / remove irrelevant branches. 

* Existing 
 - [ ] Existing WG recharter 
 - [x] Existing IG recharter
 - If this is a charter extension or revision, link a [diff from previous charter](https://services.w3.org/htmldiff), and any issue discussion:

Horizontal Reviews: apply the Github label "Horizontal review requested" to request reviews for accessibility (a11y), internationalization (i18n), privacy, and security. **Also add a "card" for this issue to the [Strategy Funnel](https://github.com/w3c/strategy/projects/2).**

Communities suggested for outreach: 

Known or potential areas of concern: 

Where would charter proponents like to see issues raised? (this strategy funnel issue, a different github repo, email, ...)
https://github.com/w3c/web-networks-charter/issues

Anything else we should think about as we review?

**Comment by r12a** [comment]
> For all Notes or other deliverables, this Interest Group will seek [horizontal review](https://www.w3.org/Guide/Charter.html#horizontal-review) for accessibility, internationalization, privacy, and security with the relevant Working and Interest Groups, and with the [TAG](https://www.w3.org/2001/tag/).

This doesn't look to me like it's the latest template text for horizontal review. Is the difference because this is an IG, or for some other reason, or should the charter template be updated?

**Comment by dontcallmedom** [comment]
I've filed https://github.com/w3c/web-networks-charter/pull/44 that updates the HR review inspired by the text in the Media & Entertainment and the WoT IGs charters. With that said, the text in the template is oriented towards the Rec-track, so it's not very clear how to adapt it to IG deliverables.

**Comment by plehegar** [comment]
Advance notice: https://lists.w3.org/Archives/Member/w3c-ac-members/2023AprJun/0017.html

**Comment by ylafon** [comment]
(No review from TAG)

**Comment by himorin** [comment]
no comment or request from i18n (except one from Richard)

**Comment by plehegar** [comment]
(No review from PING)

**Comment by ruoxiran** [comment]
no comment from APA.

**Comment by himorin** [comment]
added one PR as https://github.com/w3c/web-networks-charter/pull/45

**Comment by siusin** [comment]
Please take a look at https://github.com/w3c/web-networks-charter/pull/46

**Comment by plehegar** [comment]
AC review: https://lists.w3.org/Archives/Member/w3c-ac-members/2023OctDec/0029.html

**Comment by plehegar** [comment]
Approved: https://lists.w3.org/Archives/Member/w3c-ac-members/2023OctDec/0064.html
