### ISSUE TITLE
Update of the SHACL specifications

### ISSUE THREAD

**Issue by pchampin** [w3c/strategy#448]
The [SHACL CG](https://www.w3.org/groups/cg/shacl/) is organizing for proposing a new version of the [SHACL](https://www.w3.org/TR/shacl/) specifications. One of the goal is to align with the upcoming release of RDF 1.2 and SPARQL 1.2. See

* https://lists.w3.org/Archives/Public/public-shacl/2024Feb/0000.html
* https://github.com/w3c/shacl/issues/26

This is still early stage incubation.

**Comment by pchampin** [comment]
See #476

**Comment by plehegar** [comment]
Closing since this is now tracked in https://github.com/w3c/strategy/issues/476
