### ISSUE TITLE
[wg/aria] Add SVG-AAM 

### ISSUE THREAD

**Issue by plehegar** [w3c/strategy#465]
Idea is to make the SVG-AAM part of the ARIA WG, as a joint deliverable or completely within ARIA.

See also https://github.com/w3c/strategy/issues/432

cc @caribouW3 @dirkschulze @jnurthen @spectranaut

**Comment by daniel-montalvo** [comment]
Done. See https://w3c.github.io/charter-drafts/2024/aria-charter.html
