### ISSUE TITLE
Verifiable Claims TF

### ISSUE THREAD

**Issue by wseltzer** [w3c/strategy#5]
_From @tidoust on October 12, 2016 7:3_

null

_Copied from original issue: tidoust/strategy#9_

**Comment by sideshowbarker** [comment]
https://lists.mozilla.org/pipermail/dev-platform/2016-December/016700.html from @ekr

> There has been a huge amount of work on using crypto to allow
you to prove specific claims without information leakage (cf.
https://www.microsoft.com/en-us/research/project/u-prove/), but this
doesn't seem to reflect any of it, rather opting for a much  more naive
design which is going to have much worse privacy properties.

**Comment by ekr** [comment]
To elaborate on this a bit, the current design appears to allow the Issuer and the Inspector to determine the identity of people proving various claims. I.e.,

- I register with identity A and prove to the Issuer that I am over 21.
- I go to a merchant and try to buy some alcohol and it asks for a proof of age.
- I go to the issuer and get a verifiable claim of age and present it to the merchant (inspector)
- The merchant can then collude with the issuer to know that it's me buying alcohol.

Note that this does not rely on having an identifier attached to the claim as long as the claim itself is unique (the typical construction is to have it be tied to an asymmetric key key). U-prove and the like use blind signatures to provide unique claims that are not known to the issuer, but I don't see that here.

**Comment by wseltzer** [comment]
Chartered. https://www.w3.org/2017/vc/
