### ISSUE TITLE
PNG maintenance and development

### ISSUE THREAD

**Issue by svgeesus** [w3c/strategy#58]
The first version of PNG was done on a mailing list, and independent of W3C. It was then published a Proposed Rec. 

The original group of people that wrote PNG  still functions to discuss PNG and to consider updates to the specification (via an extension registry not by changes to the main spec). It has occasional bursts of activity. It has it's own, lightweight, process involving a minimum duration of involvement before getting to vote.
You can see that not much happens by looking at the revision history section in
http://www.libpng.org/pub/png/spec/register/pngreg-1.4.6-pdg.html
and
http://www.libpng.org/pub/png/spec/register/pngext-1.4.0-pdg.html

The second edition was done jointly with ISO. It included errata from the first edition, but the majority of the work was to comply with ISO requirements on wording and document structure, and to then ensure the resulting spec was technically identical to the original wording. Having gone through that process, it was a lot of effort for little gain.

The ISO and W3C versions of PNG second edition are precisely identical, except for the cover pages. The W3C one is free and the ISO one is on paper and costs money. Copyright is joint; W3C copyright on ours, ISO copyright on theirs.

The APNG proposal was voted on but  rejected (I voted in favour). Since then it had a little implementation (in Mozilla and in the old, Presto-based Opera). In 2016 Apple also added support (at the OS level, for the iOS iMessage app).
http://caniuse.com/#search=apng

Google was always opposed because they wanted to promote WebP instead, although that continues to be discussed and experimental (non-shipping) support is going in as of July 2016:
https://bugs.chromium.org/p/chromium/issues/detail?id=1171
and now seesm to be ready to ship
https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/KcMjmFOgG2w

Microsoft was neither for or against. There is a uservoice for it
https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6513393-apng-animated-png-images-support-firefox-and-sa

It would be valuable to get the APNG spec rolled back into the PNG spec (MNG is a separate, and largely failed, specification). However, from a W3C perspective, that was only worth doing if at least one of Google or Microsoft planned to ship APNG support in their browser. Getting support into the main libpng software library would also be a benefit.

That work would also roll in the extensions:
http://www.libpng.org/pub/png/spec/register/pngreg-1.4.6-pdg.html
http://www.libpng.org/pub/png/spec/register/pngext-1.4.0-pdg.html

**Comment by svgeesus** [comment]
The original PMNG group has become active again recently and is discussing adding EXIF to PNG. Will see how that discussion and eventual vote goes.

**Comment by svgeesus** [comment]
http://caniuse.com/#feat=apng

**Comment by swickr** [comment]
[APNG spec](https://wiki.mozilla.org/APNG_Specification) 

> Authors:
>  Stuart Parmenter <pavlov@pavlov.net>
>  Vladimir Vukicevic <vladimir@pobox.com>
>  Andrew Smith <asmith16@littlesvr.ca>
> ...
> last modified on 26 September 2015, at 03:02.

**Comment by svgeesus** [comment]
Those are both the same version, 0.10.
The issue is that, due to significant adoption, this should be re-voted and rolled into the main PNG specification, and both the W3C and ISO versions updated.

**Comment by svgeesus** [comment]
Several mentions of APNG at the [W3C Workshop on Digital Publication Layout and Presentation (from Manga to Magazines)](https://www.w3.org/2018/publayout-workshop/minutes.html#section3-4)

**Comment by svgeesus** [comment]
A reasonably complete [testsuite](https://philip.html5.org/tests/apng/tests.html)

**Comment by svgeesus** [comment]
Chrome shipped APNG support, not behind a flag, on by default, with [Chrome 59](https://www.chromestatus.com/features/6691520493125632) so it is just Edge holding out now.

**Comment by plehegar** [comment]
Safari preview has APNG support now https://webkit.org/blog/9621/release-notes-for-safari-technology-preview-95/

**Comment by svgeesus** [comment]
Also using the [`image/apng` Media Type,(https://wiki.mozilla.org/APNG_Specification#MIME_type) which is unregistered at IANA due to lack of an authoritative spec.

I think its time to start a PNG CG to maintain this spec and to roll in APNG into the main spec.

**Comment by svgeesus** [comment]
This came up again recently, the ColorWeb CG wants [a new PNG chunk for CICP](https://github.com/w3c/ColorWeb-CG/issues/11)

**Comment by svgeesus** [comment]
The original PNG Group mailing list is now moribund.

**Comment by svgeesus** [comment]
A major issue for any new work is getting support into [libpng](http://www.libpng.org/pub/png/libpng.html) which is a very mature library, but one which has not had updates in terms of new features for some time.

**Comment by svgeesus** [comment]
Libpng has an [issue about adding APNG support](https://github.com/glennrp/libpng/issues/267), which comes down to waiting for a specification update.

**Comment by svgeesus** [comment]
An [Editors Draft for PNG]( https://w3c.github.io/PNG-spec/ ) is now being maintained, rolling in all errata.

**Comment by svgeesus** [comment]
An updated REC could be published (CR -> PR -> Rec) for just the errata, including substantive change.

New features would need a W3C Working Group.

ISO/IEC JTC1 SC24 should be notified when the errata-ed spec goes to CR so they can apply the same changes to 

> Information technology — Computer graphics and image processing — Portable Network Graphics (PNG): Functional specification. ISO/IEC 15948:2003 (E)

Question is whether to combine the two steps or do them sequentially. The alue of a new PNG Rec with very minor errata fixes, updated references etc seems minimal if it doesn't also document the widely-supported APNG extensions.

Such a specification would also allow libpng to add official APNG support rather than each browser, linux distro etc all supporting their own patched versions.

**Comment by svgeesus** [comment]
WPT has just [three tests for APNG](https://github.com/web-platform-tests/wpt/tree/master/apng) as of Mar 2021. This should be substantially expanded.

**Comment by svgeesus** [comment]
[Browsers are using `image/apng`](https://hg.mozilla.org/mozilla-central/rev/f29c9642fbca), particularly for `srcset`, which is unregistered. A PNG specification update should add the `image/apng` IANA Media Type registration template to the spec, and register it at CR.

**Comment by svgeesus** [comment]
[Draft charter](https://w3c.github.io/charter-drafts/png-2021.html), Advance notice sent 18 May 2021

**Comment by samuelweiler** [comment]
Funnel issue on chartering: https://github.com/w3c/strategy/issues/268

**Comment by dontcallmedom** [comment]
given the separate issue on the draft charter, I propose closing this and moving to strategy work concluded
