### ISSUE TITLE
SVG maintenance post-1.1

### ISSUE THREAD

**Issue by svgeesus** [w3c/strategy#59]
How to maintain and develop SVG in the face of browser disinterest in SVG 2

**Comment by grorg** [comment]
It might be interesting to investigate what happened that caused the group to get so disconnected from implementors. We (the W3C members) should have anticipated this situation years ago.

I also suggest separating maintenance from development of new features.

**Comment by svgeesus** [comment]
All good points. Yes, maintenance and development are separate issues. And indeed, not maintaining a critical mass of browser-developers started to happen a couple of years ago.

**Comment by svgeesus** [comment]
**SVG 2 feature support**

https://docs.google.com/spreadsheets/d/1kkqzcxY53h7liRYppLSSFG2sjaJ8V8TCP5rWLZK0AxA/edit#gid=0

**Comment by svgeesus** [comment]
Draft charter to add SVG to CSS WG (advance notice phase)
https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FStyle%2F2016%2Fcss-2016.html&doc2=https%3A%2F%2Fwww.w3.org%2FStyle%2F2016%2Fcss-2016%2Bsvg.html

**Comment by svgeesus** [comment]
Background, by Tav from Inkscape
http://tavmjong.free.fr/svg2_status.html

**Comment by svgeesus** [comment]
Putting SVG in CSS WG is not going to work.

**Comment by wseltzer** [comment]
@svgeesus, you mentioned a new approach. Can you link the draft charter here?

**Comment by wseltzer** [comment]
https://www.w3.org/2017/04/svg-2017.html shared with AC for comment

**Comment by wseltzer** [comment]
Florian recommended this reading from Amelia Bellamy-Royds:  http://codepen.io/AmeliaBR/post/me-and-svg

**Comment by wseltzer** [comment]
https://www.w3.org/2017/04/svg-2017.html

**Comment by wseltzer** [comment]
Charter AC review closes 17 July: https://www.w3.org/2002/09/wbs/33280/SVG-2017/results (member view of results)

**Comment by wseltzer** [comment]
SVG re-chartered 2 August.
