### ISSUE TITLE
Publishing WG

### ISSUE THREAD

**Issue by wseltzer** [w3c/strategy#6]
_From @tidoust on October 12, 2016 7:3_

null

_Copied from original issue: tidoust/strategy#8_

**Comment by iherman** [comment]
The advance notice to the AC has been sent out: https://lists.w3.org/Archives/Member/w3c-ac-members/2017JanMar/0031.html

**Comment by iherman** [comment]
As a reference:

* [Charter](https://w3c.github.io/dpubwg-charter/) in a readable form on github.io
* [Open issues](https://github.com/w3c/dpubwg-charter/issues) are on github

**Comment by iherman** [comment]
Had the first [Publishing BG F2F](https://www.w3.org/2017/03/13-pbg-minutes.html) meeting, which resulted in a lot of open issues closed (after some editing on the charter) or in Pull Request waiting for the commenters' reply.

The current plan is to have the charter in the AC's hands by the AC meeting in Beijing. Explicit outreach to some parties (eg, browser manufacturers) will be done by the BG, with the first steps already taken.

**Comment by iherman** [comment]
Got a review from r12a on internationalization[1], charter text has been changed.

1. https://github.com/w3c/dpubwg-charter/issues/36
2. https://github.com/w3c/dpubwg-charter/pull/38

**Comment by iherman** [comment]
For the records, the charter is now in the hands of the AC:

https://lists.w3.org/Archives/Member/w3c-ac-members/2017AprJun/0006.html

**Comment by iherman** [comment]
Publishing WG started: https://www.w3.org/publishing/groups/publ-wg/
