### ISSUE TITLE
Navigation Transitions

### ISSUE THREAD

**Issue by ylafon** [w3c/strategy#65]
Might be useful in many cases, including digital publishing, so here is the start of the thread:

https://lists.w3.org/Archives/Team/team-strat/2016Dec/0000.html

**Comment by iherman** [comment]
This is definitely relevant for publishing. In some areas, like children's books, mangas and cartoons, maybe even educational publishing, people have already looked at the issue of how to control transition from one 'slide' or image to the other. Note, however, that these came up primarily when the main content (eg, in an ebook) are a series of SVG files, not HTML files.

I had some contact with a person called Samuel Petit (at a place called [Sequencity](https://www.sequencity.com/) who made a really great presentation at a conference in spring 2016 in Bordeaux on this subject. I thought I was successful in convincing him that he should join the DPUB IG (at least as an IE), but it did not happen. He would be a good person for real life use cases in this area, though.

**Comment by iherman** [comment]
(Have added this to the exploration column of the funnel.)

**Comment by svgeesus** [comment]
This is a specific, presentational aspect of a more general problem - that current Web architecture conflates the (textual) content of a page with the manifest (styles, scripts, etc). This gives a problem when some parts (scripting, styling, state) are specified along with one set of content (one page) but then you want to move to new content (new page) and run CSS or scripts during that move.

The summary of experiments at https://github.com/jakearchibald/navigation-transitions/blob/master/README.md is useful

**Comment by svgeesus** [comment]
No updates to [Navigation transitions](https://github.com/jakearchibald/navigation-transitions/commits/master/README.md) since 2017. 

This is a significant issue, but there does not seem to be a specific solution proposed at this time.
