### ISSUE TITLE
Container Queries

### ISSUE THREAD

**Issue by svgeesus** [w3c/strategy#69]
From the Responsive Issues Community Group 
http://ricg.io/

**Comment by svgeesus** [comment]
Also being discussed in CSS WG
https://github.com/w3c/csswg-drafts/issues/1031

**Comment by dontcallmedom** [comment]
active work happening on this in the CSS Working Group as part of the CSS Contain spec, so moving to evaluation (maybe should be "strategy work concluded"?)

**Comment by svgeesus** [comment]
[CSS Contain 3, section 4. Container Queries](https://drafts.csswg.org/css-contain-3/#container-queries)

**Comment by svgeesus** [comment]
Closing as the work is being developed in CSS WG
