### ISSUE TITLE
Rechartering churn with new deliverables from incubation

### ISSUE THREAD

**Issue by svgeesus** [w3c/strategy#70]
As each new item of work comes into an existing WG from incubation, a new deliverable is added to the charter. This requires AC review, which requires staff to push on AC reps (collectively and individually)  to respond to the review so we meet the 5% participation bar. 

This was okay, when it happened every 2 to 3 years per WG. With the move to incubation for each individual piece of work, then especially for highly modular specifications, we could be rechartering every one to three *months*.

The staff time implications of that are significant, as is the risk of wearing down the AC with many hundreds of charter reviews a year. It makes W3C less agile.

**Comment by iherman** [comment]
I do have the feeling that we may have to re-consider/re-discuss this whole 'incubation' model. Beyond the issue you are raising (and I do not have a direct answer to it), it is also a dangerous path: what this means is that all creative work is done outside of the Working Groups, with WG-s only providing IPR protection and rubber stamping.

If this becomes _THE_ exclusive model, then I do not see any justification for a number of institutions to join W3C, which erodes our current business model. More importantly, it does not ensure the proper representation of many communities in developing new standards either, and relinquishes the control to a narrow group of powerful members and some independent developers, whose interest are not the Web at large but are dictated by their own business goals. We already see these distortions today.

(I do not think SVG would exist today, for example, had we had the same development model at the time when SVG started...)

**Comment by wseltzer** [comment]
Different types of charter review: 
* New WG
* New deliverable to existing WG
* Maintenance of existing deliverable
