### ISSUE TITLE
Temporal and probabilistic annotations for RDF

### ISSUE THREAD

**Issue by philarcher** [w3c/strategy#75]
RDF triples can be collected in named graphs and statements made about those triples. Reification has also been a feature of RDF since the beginning. However, the topic keeps coming up for how one can assert that a triple holds for a defined period of time, or that it is true with x% probability. The ideas have been the basis of experiments but nothing concrete has emerged and there's no consensus as yet. One *possible* way forward might be some additional syntax for up to 7 tuples that can be transformed into one-triple named graphs. Too early to say.

An EU project proposal being submitted in April 2017 includes provision for a workshop on this topic which is relevant to:
+ big data analytics;
+ AI
+ machine learning
+ '[Cognitive Web](https://github.com/w3c/strategy/issues/60)'
+ search

**Comment by philarcher** [comment]
I reckon this one can be closed - Dave's recent workshop covered this topic https://www.w3.org/Data/events/data-ws-2019/cfp

**Comment by pchampin** [comment]
Following the Graph Data workshop, a "task force" inside the RDF-DEV Community Group has emerged, with the goal to produce a specification of RDF-star (formerly known as RDF*).

https://w3c.github.io/rdf-star/

We have released our first public draft recently:
https://w3c.github.io/rdf-star/cg-spec/2021-02-18.html

**Comment by pchampin** [comment]
> I reckon this one can be closed - Dave's recent workshop covered this topic https://www.w3.org/Data/events/data-ws-2019/cfp

Agreed (as pointed out above). Note that we (the RDF-star "task force") are currently working on a WG charter.
