### ISSUE TITLE
WebPlatform recharter; Service Workers charter

### ISSUE THREAD

**Issue by wseltzer** [w3c/strategy#77]
WebPlatform is considering recharter to add deliverables from WICG (Intersection Observer, Static Range) and remove deliverables (Service Workers; Background synchronization). +6mo

Service Worker and Background Sync would move to a separate group.

**Comment by iherman** [comment]
I am surprised and worried about the fact that Service Workers are removed; they are important for publishing (and, administratively, they are listed explicitly in the upcoming publishing wg charter as part of the liaison with the WPWG). 

What is the story there?

Ivan

---
Ivan Herman
Tel:+31 641044153
http://www.ivan-herman.net

(Written on mobile, sorry for brevity and misspellings...)

**Comment by wseltzer** [comment]
@iherman the preliminary plan is to move Service Worker to a separate, focused group. We're aiming to get more detail here soon.

**Comment by iherman** [comment]
> @iherman <https://github.com/iherman> the preliminary plan is to move Service Worker to a separate, focused group. We're aiming to get more detail here soon.
> 

Ah! That sounds much better:-)

But, I presume, we can safely ignore this fact in the publishing charter. I mean the new group will then "inherit" the liaison.

**Comment by wseltzer** [comment]
And here's the draft Service Workers WG charter: https://w3c.github.io/charter-drafts/sw-charter.html

**Comment by wseltzer** [comment]
Advance notice sent: https://lists.w3.org/Archives/Public/public-new-work/2017May/0006.html

**Comment by wseltzer** [comment]
Discussion welcomed in the charters' github repositories:    
http://w3c.github.io/charter-html/webplat-wg.html -> https://github.com/w3c/charter-html/
http://w3c.github.io/charter-drafts/sw-charter.html ->  https://github.com/w3c/charter-drafts/

**Comment by wseltzer** [comment]
Both charters approved 2 August. WebPlatform re-chartered and Service Workers started.
