### ISSUE TITLE
Permissions and User Consent Workshop

### ISSUE THREAD

**Issue by wseltzer** [w3c/strategy#78]
Devices and Sensors, Feature Policy, Permissions API - all deal with security and privacy considerations. How can we do so consistently and effectively for the platform?

**Comment by wseltzer** [comment]
Early thinking (team-only): https://www.w3.org/Team/wiki/Permission_workshop

**Comment by samuelweiler** [comment]
Workshop announced  https://lists.w3.org/Archives/Member/w3c-ac-members/2018JulSep/0008.html

**Comment by wseltzer** [comment]
Report pending

**Comment by samuelweiler** [comment]
[Report](https://www.w3.org/Privacy/permissions-ws-2018/report.html)

Related output: [“Adding another permission? A guide”](https://github.com/w3cping/adding-permissions/blob/master/README.md)
