### ISSUE TITLE
EOWG

### ISSUE THREAD

**Issue by wseltzer** [w3c/strategy#79]
Extended with notice of work on new charter.

**Comment by wseltzer** [comment]
Advance notice of rechartering: https://lists.w3.org/Archives/Public/public-new-work/2017May/0010.html
https://www.w3.org/WAI/EO/charter2017

**Comment by swickr** [comment]
[Mike Champion raises concerns to AB](https://www.w3.org/Payments/IG/wiki/Main_Page/Charter2017)

**Comment by wseltzer** [comment]
Rechartered.
