### ISSUE TITLE
Media Capabilities

### ISSUE THREAD

**Issue by tidoust** [w3c/strategy#87]
To improve the user experience and take advantage of advanced device capabilities when they are available, media providers need to know the decoding (and encoding) capabilities of the user's device. Can the device decode a particular codec at a given resolution, bitrate and framerate? Will the playback be smooth and power efficient? Can the display render HDR and wide color gamut content? The [Media Capabilities](https://wicg.github.io/media-capabilities/) specification defines an API to expose that information, with a view to replacing the more basic and vague `isTypeSupported()` and `canPlayType()` functions defined in HTML.

The APIs will expose information about the decoding and encoding capabilities for a given format but also output capabilities to find the best match based on the device’s display.

Incubated in the [Web Platform Incubator CG](https://www.w3.org/community/wicg/)

**Comment by svgeesus** [comment]
relates to https://github.com/w3c/strategy/issues/18 for querying gamut and HDR capability
https://wicg.github.io/media-capabilities/#display-capabilities

**Comment by tidoust** [comment]
Mounir shared progress on the Media Capabilities with the Media & Entertainment IG last week. A [summary of the outcomes and of questions raised by IG participants](https://lists.w3.org/Archives/Public/public-web-and-tv/2017Dec/0004.html) is available.

**Comment by sideshowbarker** [comment]
Safari Technology Preview 66 shipped with the Media Capabilities API as an Experimental Feature

https://developer.apple.com/safari/technology-preview/release-notes/

**Comment by tidoust** [comment]
In scope of chartered [Media WG](https://www.w3.org/media-wg/)
