### ISSUE TITLE
Archival and the Web

### ISSUE THREAD

**Issue by iherman** [w3c/strategy#91]
There has been some discussion with experts in the Hathi Trust, University of Michigan, but we also know about the interest of University of Illinois, all major (national) libraries, Getty, etc: Web content, ie, audio or video data, Web publications,  Web Applications, etc, are all potential targets for long-term archival and preservation. However, archival may raise a number of special questions in terms of associated (meta)data, how to store the relevant versions of dynamic environments like video players or Javascript libraries, etc.

Latest discussions raised the possibility of organizing a Workshop (possibly before TPAC'17) to explore this area.

**Comment by swickr** [comment]
Another perspective on archival [digital] content is the [Museums and the Web](http://www.museumsandtheweb.com/researchForum.html) community.

**Comment by liamquin** [comment]
See also http://netpreserve.org/ga2018/call-for-papers/

There was also a Balisage (or possibly Extreme Markup) symposium on the opposite direction, how best to make information last "for the long haul"

**Comment by iherman** [comment]
The upcoming [Digital Publishing Summmit](https://www.edrlab.org/dpub-summit-2018/) will include a session on archival. Although centered on publishing, that may give some more insight.

**Comment by TzviyaSiegman** [comment]
I would love to see formal archiving requirements for publishing on the Web. It is important for the group that defines Publishing standards (for HTML or Publications) to also define archiving standards. We have already seen other organizations begin work on archiving EPUB (See NISO's archiving metadata https://www.iso.org/standard/73169.html). National libraries and archives cannot store documents of records unless we create an archivable format.

**Comment by iherman** [comment]
The specific issue on an Archival Workshop is now in a separate issue #147; closing this one to avoid duplication.

Cc: @wseltzer
