### ISSUE TITLE
Compression API

### ISSUE THREAD

**Issue by siusin** [w3c/strategy#93]
discourse: [https://discourse.wicg.io/t/need-for-gzip-deflate-api/1237](https://discourse.wicg.io/t/need-for-gzip-deflate-api/1237)

Most of the members in the WebPerf WG gave [+1](https://www.w3.org/2017/06/20-webperf-minutes.html#item10) to this proposal, and @yoavweiss has kindly offered his help to move this forward :) 

Given that compression is such a common problem of the web platform, we are not sure whether we should set limit to the API (within the scope of WebPerf?)... Any thoughts?

**Comment by plehegar** [comment]
The webperf charter is at
 http://www.w3.org/2016/07/webperf

My reading of the scope section is that a gzip api is larger than the current webperf scope, we need to update the charter to include in its scope/deliverables. @wseltzer , do you concur?

**Comment by wseltzer** [comment]
On 06/29/2017 12:15 PM, Philippe Le Hegaret wrote:
> The webperf charter is at
>  http://www.w3.org/2016/07/webperf
> 
> My reading of the scope section is that a gzip api is larger than the current webperf scope, we need to update the charter to include in its scope/deliverables. @wseltzer , do you concur?
> 

The scope is pretty broad: "user agent features and APIs to observe and
improve aspects of application performance." If the group wants to add
it, compression isn't among the specific exclusions.

--Wendy

-- 
Wendy Seltzer -- wseltzer@w3.org +1.617.715.4883 (office)
Strategy Lead, World Wide Web Consortium (W3C)
https://wendy.seltzer.org/        +1.617.863.0613 (mobile)

**Comment by plehegar** [comment]
@siusin the webperf can go ahead then without a need to update its charter. Close this issue if you concur.

**Comment by siusin** [comment]
ok, thanks both!
