### ISSUE TITLE
Web and Networks IG (was Web 5G)

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/strategy#97]
5G and other major network evolutions (e.g. Multi-Access Edge Computing MEC) are expected to have a transformative effect on connected applications, and expect themselves more in-depth integration between apps and networks.

Web5G is how we call the exploration of the intersection between the evolution of networking techs and Web techs.

[Draft CfP for a possible workshop](https://w3c.github.io/web5g-workshop/) on the topic

**Comment by nitedog** [comment]
- https://www.w3.org/community/acweb/
- https://www.w3.org/wiki/TPAC/2017/SessionIdeas#Web5G_Based_Communications_Accessibility

**Comment by dontcallmedom** [comment]
workshop now [officially announced for Jan 22-23](https://www.w3.org/2017/11/web5g-workshop/)

**Comment by wseltzer** [comment]
A [draft Web and Networks IG charter](https://www.w3.org/2019/03/web-networks-charter-draft.html) is under review.

**Comment by wseltzer** [comment]
WG launched https://www.w3.org/2019/05/web-networks-ig-charter.html
